### ISSUE TITLE
fout in prioriteit bij instellen voorkeuren

### ISSUE THREAD

**Issue by BoerenWorks** [Amsterdam/fixxx-pakjekraam#109]
Wanneer een VPL één voorkeursplek opgeeft of wijzigt, dan verschijnt in de feedback achter die voorkeur de verkeerde voorkeurs-prio (hier nr 4). Het lijkt of hij optelt ipv de juiste prio te tonen.

![image (1)](https://user-images.githubusercontent.com/22602297/59765919-672d7b00-929f-11e9-89dc-6a0162fa5e6f.png)

Dit is de voorkeur zoals hij is ingesteld door de vph

![image (2)](https://user-images.githubusercontent.com/22602297/59766016-95ab5600-929f-11e9-9a8b-5c98e392934b.png)

**Comment by rutgerdik** [comment]
is gefixt
