### ISSUE TITLE
bij voorkeurenscherm aangeven welke vpl je al hebt (als dat zo is)

### ISSUE THREAD

**Issue by BoerenWorks** [Amsterdam/fixxx-pakjekraam#111]
het zou makkelijk zijn als ik hier ook mijn ‘vaste’ plaats vermeld zou zien. (feature, geen bug)

<img width="716" alt="image" src="https://user-images.githubusercontent.com/22602297/59788854-f00edb80-92cc-11e9-8e84-a3a4b4f65267.png">

**Comment by rutgerdik** [comment]
is gefixt
