### ISSUE TITLE
vpl met aantal kramen alleen verschuiven als het past

### ISSUE THREAD

**Issue by BoerenWorks** [Amsterdam/fixxx-pakjekraam#112]
F Hessing wil graag verplaatsen naar plaatsen 5,6,7. De plaatsen 5,6 zijn vrij, plaats 7 niet. Ik zou dan verwachten: niet verschuiven. Maar het systeem doet dat wel en krimpt zijn drie kramen gewoon in naar twee. Ik noem het een bug maar dat is het 'eigenlijk' niet want gewoon nog niet zo gebouwd. Maar het is wel heel belangrijk!

**Comment by tjoekbezoer** [comment]
Is gefixed in #337.
