### ISSUE TITLE
marktmeester: ik zou graag broodkruimels bovenaan zien

### ISSUE THREAD

**Issue by BoerenWorks** [Amsterdam/fixxx-pakjekraam#115]
ik wordt als marktmeester ingelogd helemaal gek van het terug gaan met de terugtoets. waarom niet een mooie broodkruimel. nu is markten wel al klikbaar, daar graag dingen achter? bijvoorbeeld markten > plein 40 -45 > indelingslijst (waarbij de laatste de pagina is waar ik op zit en dus niet klikbaar is). Het is zo hinderlijk dat ik het ook de status bug meegeef...

**Comment by yvonnetjan** [comment]
Bij demos aan marktmeester is ook behoefte om snel in de linkslijst van een markt terug te komen nadat ze de aan/afwezigheid of plaatsvoorkeur hebben aangegeven. De link van de markt leidt naar de vaste plaatshouders lijst. Beter is als deze linkt naar het overzicht van de links van die markt.

**Comment by evaleffef** [comment]
In het design system staat een voorbeeld hoe dit aan te pakken: https://designsystem.amsterdam.nl/7awj1hc9f/p/35ca97

**Comment by evaleffef** [comment]
@evaleffef TODO: uitzoeken specifieke pagina's
