### ISSUE TITLE
Sollicitantenlijst vorige / volgende knoppen verwijzen naar foute lijst

### ISSUE THREAD

**Issue by BoerenWorks** [Amsterdam/fixxx-pakjekraam#116]
sollicitantenlijsten en vasteplaatshouderslijsten hebben vorige/volgende knoppen die uitkomen in de indelingslijst

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/22602297/59788583-59dab580-92cc-11e9-90e3-60d452093836.png">

**Comment by BoerenWorks** [comment]
vorige / volgende als in dinsdag / donderdag...

**Comment by rutgerdik** [comment]
Knoppen zijn uit de soll lijst gehaald.
