### ISSUE TITLE
Indelingslijst, contrast zwart op blauw is niet ok

### ISSUE THREAD

**Issue by BoerenWorks** [Amsterdam/fixxx-pakjekraam#118]
zwart op blauw kan beter wit op blauw zijn... 

<img width="189" alt="image" src="https://user-images.githubusercontent.com/22602297/59788498-2566f980-92cc-11e9-850c-1723267a5cf2.png">

**Comment by Robbert** [comment]
Ook:

<img width="46" alt="Screenshot 2019-06-24 at 17 22 28" src="https://user-images.githubusercontent.com/30694/60031274-b5c68500-96a4-11e9-94e1-d040444a2a1d.png">

**Comment by evaleffef** [comment]
Eerst kleuren straktrekken, als dan nog voorkomt opnieuw oppakken
