### ISSUE TITLE
Indelingslijst, hoog nummer past niet

### ISSUE THREAD

**Issue by BoerenWorks** [Amsterdam/fixxx-pakjekraam#120]
koopmannen met een hoog ancienniteitsnummer passen niet in de tabel. zou wel moeten. 
<img width="336" alt="image" src="https://user-images.githubusercontent.com/22602297/59788144-63afe900-92cb-11e9-994b-f1c5a52f9d55.png">

**Comment by rutgerdik** [comment]
Gefixt
