### ISSUE TITLE
Plaatsvoorkeuren worden doorgevoerd voor alle markten

### ISSUE THREAD

**Issue by yvonnetjan** [Amsterdam/fixxx-pakjekraam#122]
Wanneer een gebruiker enkele plaatsvoorkeuren bij 1 markt doorvoert(bijv. Albert Cuijp), dan verschijnen die plaastvoorkeuren ook in het overzichscherm als plaatsvoorkeuren bij alle andere markten

**Comment by rutgerdik** [comment]
Mogelijk een issue als we een volgende markt aansluiten

**Comment by rutgerdik** [comment]
gefixt
