### ISSUE TITLE
Kraamnummer van VKK bestaat niet

### ISSUE THREAD

**Issue by Robbert** [Amsterdam/fixxx-pakjekraam#128]
We tonen in de interface een kraamnummer dat voor intern gebruik is, verwarrend voor de ondernemer.

<img width="425" alt="Screenshot 2019-06-20 at 18 00 01" src="https://user-images.githubusercontent.com/30694/59863619-57886200-9385-11e9-947a-6e0311689f88.png">

**Comment by rutgerdik** [comment]
Gefixt, VKK ondernemers zien geen plaatsen meer
