### ISSUE TITLE
Niet meer mogelijk te kiezen welke kraam je het liefste wilt

### ISSUE THREAD

**Issue by Robbert** [Amsterdam/fixxx-pakjekraam#129]
Met de nieuwe interface die automatisch een naastliggende plaats kiest, kun je voor een ondernemer die wil inkrimpen van 2 naar 1 plaats, niet aangeven dat je liever op 12 dan op 11 wilt staan.

<img width="350" alt="Screenshot 2019-06-20 at 21 55 01" src="https://user-images.githubusercontent.com/30694/59877441-29674a00-93a6-11e9-9241-83b29938361e.png">

**Comment by rutgerdik** [comment]
vervalt, voorkeuren kiezen is aangepast
