### ISSUE TITLE
Plaatsnummer separator niet consistent

### ISSUE THREAD

**Issue by Robbert** [Amsterdam/fixxx-pakjekraam#136]
Op `/dashboard/`:

<img width="254" alt="Screenshot 2019-06-21 at 11 13 41" src="https://user-images.githubusercontent.com/30694/59912127-b09fd680-9415-11e9-9fe1-5936ed5edd40.png">
<img width="115" alt="Screenshot 2019-06-21 at 11 13 39" src="https://user-images.githubusercontent.com/30694/59912128-b09fd680-9415-11e9-8be0-aab6cf56f276.png">

**Comment by rutgerdik** [comment]
fixed
