### ISSUE TITLE
Plein 40-45 Vaste koopman met 2 kramen kan 2 kramen met loopje er tussen kiezen in plaatsvoorkeuren

### ISSUE THREAD

**Issue by yvonnetjan** [Amsterdam/fixxx-pakjekraam#151]
In productie. Een vaste koopman die 2 kramen heeft, test in usability-test of hij 2 bepaalde kramen kan kiezen. Hij kiest nr 29 en 30, en die keuze lukt. Echter er zit een loopje tussen deze twee kramen. De kramen zouden nooit naast elkaar als voorkeur opgegeven mogen worden.

**Comment by rutgerdik** [comment]
vervalt, voorkeuren kiezen is aangepast
