### ISSUE TITLE
Plein 40-45: vaste plaatshouder met 2 vaste kramen op kaart en in de indelingslijst maar 1 vaste plaats in plaatsvoorkeuren

### ISSUE THREAD

**Issue by yvonnetjan** [Amsterdam/fixxx-pakjekraam#158]
De VPH van 21 en 22
Hebben in de indelingslijst 2 plaatsen, maar bij het wijzigen van plaatsvoorkeuren staat maar 1 vaste plaats (ipv 2).

**Comment by rutgerdik** [comment]
Gefixt
