### ISSUE TITLE
Kraamnummers en soll.nummers niet zichtbaar in indelingslijst

### ISSUE THREAD

**Issue by yvonnetjan** [Amsterdam/fixxx-pakjekraam#185]
In de indelingslijsten zijn de kraamnummers en sollicitatienummers op een aantal bladzijdes niet meer zichtbaar.
<img width="240" alt="kraamnummers" src="https://user-images.githubusercontent.com/51442667/60861009-18795e00-a219-11e9-913e-e405a81fb231.png">

**Comment by evaleffef** [comment]
Als bug genoteerd op de backlog

**Comment by rutgerdik** [comment]
als bug genoteerd op de backlog
