### ISSUE TITLE
E-mail adres wordt niet vooringevuld bij activeren

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#250]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/22743290/61590370-74989680-abb8-11e9-8e55-e2f0ca38dfa6.png">
Het e-mailadres van de ondernemer is wel bekend in Mercato (en dus Makkelijke Markt api), maar wordt niet getoond bij activatie in Keycloack. Wordt het mailadres niet meegenomen uit de api? Of enkel niet getoond in de Keycloack flow?

**Comment by evaleffef** [comment]
Dit is niet relevant (meer), ik sluit deze issue.
