### ISSUE TITLE
E-mail met plaatstoewijzing wordt ook verstuurd voor niet-marktdagen

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#252]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/22743290/61590450-d3aadb00-abb9-11e9-99fe-cf78d9beb49a.png">
De e-mails met toewijzingen worden (nu in acceptatie althans) ook verstuurd voorafgaand aan dagen dat er geen markt is. Dit zou enkel moeten gebeuren wanneer er de volgende dag een markt is.

**Comment by Robbert** [comment]
Fixed.
