### ISSUE TITLE
Tekst bij aanwezigheidskalender is verdwenen

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#253]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/22743290/61590561-91829900-abbb-11e9-9cd4-ec4748b8ba97.png">
Hier stond eerder een regel tekst met aanwijzing, afhankelijk van of je een soll of vph bent, wordt een tekst getoond (Met de strekking: Vink aan wanneer u naar de markt komt / Vink uit wanneer u niet naar de markt komt).
Deze teksten moeten weer getoond worden.

**Comment by evaleffef** [comment]
Tekst moet zijn voor VPH: 'Vink uit op welke dagen u (of uw vervanger) niet op deze markt staat.'

**Comment by rutgerdik** [comment]
gefixt
