### ISSUE TITLE
Aanpassen kopje 'Mijn Markten' homepage

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#270]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/22743290/61856860-48845a80-aec3-11e9-9282-45d068ecccef.png">
De kop 'Mijn markten' moet worden 'Inloggen Mijn markten'

**Comment by evaleffef** [comment]
Graag ook koppen `Account activeren` en `Inloggen mijn markten` klikbaar maken.

![image](https://user-images.githubusercontent.com/39556722/61860347-1a564900-aeca-11e9-95fe-fb1bf027d3af.png)
