### ISSUE TITLE
Aanpassen template van Erkenningsnummer naar Registratienummer

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#273]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/22743290/61876471-3cad8e00-aeed-11e9-9d16-378cf9b9ab34.png">
In de keycloack templates moet het woord Erkenningsnummer vervangen worden door Registratienummer.
Als dit gedaan is graag seintje geven, dan kan Datapunt het verwerken.

De templates zijn al aangepast, datapunt kan de Keycloak templates in Keycloak zetten.

**Comment by mguikema** [comment]
Dit staat al klaar in onze code, datapunt moet dit alleen nog in keycloak zetten

**Comment by rutgerdik** [comment]
Gefixt
