### ISSUE TITLE
Na doorgeven en bewaren koopwaar/branche waarschuwing nog zichtbaar

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#279]
Na het activeren vul ik met een ondernemer zijn profiel in (Android/Chrome). Hij kiest `stoffen` want hij verkoopt gordijnen. Bij terugkeren in dashboard ziet hij nog steeds de waarschuwing. Als hij weer naar zijn profiel gaat, blijkt het inderdaad niet opgeslagen. Hij probeert het nog 3 x zonder succes. 

Is het mogelijk dat er een foutje in de json is geslopen? Bij andere ondernemers leek het wel goed te gaan.

![image](https://user-images.githubusercontent.com/39556722/61994861-94c8c980-b080-11e9-8b1f-3548bda42209.png)

**Comment by mguikema** [comment]
Fix commit:
https://github.com/Amsterdam/fixxx-pakjekraam/commit/f9a0806ed6d17eab6b25219e41682dd109adbc98
