### ISSUE TITLE
Favicon / Bookmark icoon voor makkelijk terugvinden op Home Screen mobiel

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#280]
Er is een duidelijk icoon nodig, voor herkenbaarheid van de link op het Home Screen van de telefoon.

Nu ziet het er zo uit als je de pagina opslaat op je Home Screen:

![image](https://user-images.githubusercontent.com/39556722/62010403-aa1a2280-b16a-11e9-9186-eefacdc90610.png)

**Comment by tomootes** [comment]
Hier wachten we even mee tot we Rutger de vermeende versie aanlevert.

**Comment by evaleffef** [comment]
![image](https://user-images.githubusercontent.com/39556722/65698495-daa00f00-e07c-11e9-8c8f-1598c29fe607.png)
