### ISSUE TITLE
Tekst in ondernemer-dashboard en boven plaatsvoorkeuren tijdens wenperiode

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#291]
De tekst is als volgt:

> Vanaf donderdag 1 augustus start de eerste fase van digitaal indelen.
> 
> Let op: Ondernemers die zich digitaal hebben aangemeld, krijgen tijdens de loting op de markt voorrang op ondernemers die zich niet digitaal hebben aangemeld.
> 
> De loting en de indeling verloopt verder zoals u gewend bent.

**Comment by mguikema** [comment]
https://github.com/Amsterdam/fixxx-pakjekraam/commit/e77e5e30e7b36aab7e20b16a53ef956e2901bf4a
