### ISSUE TITLE
Soms foutmelding in Safari - doctype

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#297]
Terwijl ik uitleg geef aan een ondernemer, opent hij Safari, gaat naar kiesjekraam.amsterdam.nl en logt hij in. Na inloggen ziet hij bijgaande foutmelding.

![image](https://user-images.githubusercontent.com/39556722/62222624-f86e3200-b3b3-11e9-9271-72689f3d4be6.png)

**Comment by mguikema** [comment]
Ik heb de bug gevonden. Het is eigenlijk de 401 error pagina, alleen de response header werd niet goed gezet, sommige browsers tonen gewoon een pagina en anderen zien de pagina als bestand. Zie screenshot 
![image](https://user-images.githubusercontent.com/1019329/62452022-a80a2200-b76f-11e9-9026-b4d1d0e28794.png)
Als de 401 is opgelost, zal deze ook verdwijnen. De bug zit dan nog wel in error handling. Dus die haal ik eruit.

**Comment by mguikema** [comment]
De foutmelding is op de markt detail en dashboard van de ondernemer een pagina geworden. Met een login link, die de gebruiker na login redirect naar de pagina waar zij/hij vandaan kwam.

**Comment by rutgerdik** [comment]
gefixt
