### ISSUE TITLE
Email sturen bij wijziging plaatsvoorkeuren en bij wijziging aanwezigheid

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#298]
Vraag is of je dit uberhaubt wilt, wanneer wel niet?

**Comment by evaleffef** [comment]
Ik sluit deze issue, omdat de manier van opslaan aangepast is (elke wijziging wordt direct opgeslagen bij aanwezigheid en plaatsvoorkeuren, niet bij profiel). Daarnaast hebben we een log gemaakt van de instellingen op het moment van de berekening.
