### ISSUE TITLE
🐛Punt in registratienummer

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#341]
Er worden nu gebruikers geactiveerd met en zonder punt in hun registratienummer. Voor sommige zijn zelfs 2 accounts in KeyCloak. 

We nemen aan dat dit soms voor problemen zorgt.

Je moet, als je geactiveerd bent met punt, ook inloggen met punt. En andersom.

Er zijn accounts die geactiveerd zijn zonder punt, voorkeuren hebben opgeslagen, gedeactiveerd zijn in KeyCloack, opnieuw geactiveerd met punt. 

### Opslaan van plaatsvoorkeuren 
Bij sommige ondernemers is er een probleem met het opslaan van de plaatsvoorkeuren (aantal kramen en flexibel indelen, zie issue #392 
### Wachtwoord vergeten proces 
- werkt ook niet goed als je met/zonder punt doet. Want als geactiveerd met punt, maar wachtwoord vergeten functie zonder punt, dan wordt de account niet gevonden.

### Account de-activeren - heractiveren
Indien een account met punt gedeactiveerd wordt, dan verdwijnen die settings niet uit de database (bijvoorbeeld plaatsvoorkeuren en/of aanwezigheid) en die hebben dan een punt.
Wordt die account vervolgens opnieuw geactiveerd in KeyCloack, maar ditmaal zonder punt, dan matchen de ondernemer gegevens niet met de reeds opgeslagen instellingen.

Zo kan het zijn dat de ondernemer mét punt nog aangemeld is voor alle dagen, maar de ondernemer zonder punt meldt zich naar na af -> ondernemer wordt ingedeeld.

Bovenstaande situatie geldt ook andersom.

### E-mail na indeling
Bij het versturen van de e-mails naar de aangemelde ondernemers wordt er een query gedaan op KeyCloack : zoek alle ondernemers. Daarmee wordt een match gedaan: heeft de ondernemer een toewijzing -> kijk dan in de dataset uit KeyCloack of deze gebruiker een e-mailadres heeft. 
Als in het registratienummer van de ondernemer in Kies je kraam een punt staat, maar in KeyCloack niet, dan is er dus GEEN match en ontvangt de ondernemer GEEN e-mail.

#### Mogelijkheden - Kies je kraam - KeyCloack - Makkelijke Markt
![image](https://user-images.githubusercontent.com/39556722/65883592-a8055780-e397-11e9-902c-1b8731843fff.png)

Alleen de eerste situatie (nergens een punt) geeft de juiste werking.

## 1. voor match in e-mail script beide registratienummers cleanen van punt - #421
Voordat deze match gedaan met KeyCloack en Makkelijke Markt gedaan wordt, de punt uit het registratienummer (van de RSVP) halen.

-> Daarmee los je situatie 3 en 4 op en gaat dit onderdeel, het mailen na de indeling goed!

## 2. Activeren met . onmogelijk maken #418

Tijdens het activeren de punt uit het registratienummer verwijderen, zodat nieuwe registraties alleen zonder punt in Kies je kraam & KeyCloack bestaan.

-> Daarmee voorkom je situatie 3 in de toekomst

## 3. Accounts met . vervangen in KeyCloack

Hiervoor moet waarschijnlijk DataPunt een query draaien ?!? Wij kunnen handmatig de accountnaam niet wijzigen.

-> Hiermee los je situatie 2 op en gaat er minder fout!

## 4. Registratienummers met . in onze DB vervangen

Queries draaien waarmee we onze data kunnen nalopen en registratienummers met een punt kunnen vervangen door registratienummers zonder punt.

-> Daarmee voorkom je situatie 3 en 4 (mits stap 3. ook uitgevoerd is)

**Comment by rutgerdik** [comment]
<img width="435" alt="image" src="https://user-images.githubusercontent.com/22743290/64254460-bccd0780-cf1f-11e9-8152-07a24c074eb8.png">
Geldt bij activeren, inloggen én wachtwoord vergeten flow.

**Comment by rutgerdik** [comment]
Let op dat het nu nog mogelijk is om **tweemaal** te activeren, een zonder punt in het registratienummer, en eentje met punt. In de Keycloack userlijst komen deze entries onder elkaar te staan.
