### ISSUE TITLE
De e-mail na indeling lijkt niet te werken

### ISSUE THREAD

**Issue by rutgerdik** [Amsterdam/fixxx-pakjekraam#348]
Het lijkt erop dat er op dit moment geen mails worden verstuurd.

## verwacht gedrag

Elke avond (voorafgaand aan een marktdag) wordt om 21.00 uur (nadat de indeling heeft plaatsgevonden) een e-mail gestuurd, naar alle aangemelde ondernemers(?). 

### wenperiode

Tijdens de wenperiode (alleen aan/afmelden) bevat deze mail nog een algemene tekst en geen uitslag. 

## e-mail variaties

Zie: https://docs.google.com/spreadsheets/d/1-t8CRVEMKgcr6h5yfI2yL_s0uGqjGD9lqgJbCiI3ljQ/edit?usp=drive_web&ouid=101551014730351679715

### eggie

Als gestart wordt met schaduwdraaien en/of digitaal indelen zal de inhoud van de e-mail ook de daadwerkelijke plaatsingsnummers e.d. moeten bevatten.

Je kunt dit al zien door `eggie=true` achter de e-mail url te zetten.

## vragen

- wat triggert het versturen van een e-mail?
- hoe werkt het met afwijzingen en e-mail? Want een afwijzing wordt niet opgeslagen in de database;
- wat is het verschil tussen ACC en PROD: op prod. is een cronjob die de berekening aanroept.
- VPH's alleen die verplaatsen/vergroten zouden mail moeten krijgen.

## Testen
- Eva, heb jij een mail gehad? Zo ja, is deze gefixt.

## Technische oorzaak
- Er werden gebruikers opgevraagd aan keycloack, echter maar de eerste 100 terwijl het er 180 waren. 
- Door de punten in de gebruikersnamen matchte de data uit Makkelijke Markt en en Keycloack niet meer, zie ook #341

**Comment by evaleffef** [comment]
@tom: ik ben bang dat ik deze niet kan testen zolang het niet op PROD staat

**Comment by evaleffef** [comment]
✅ e-mail van indeling ontvangen!
