### ISSUE TITLE
Wijziging indelingsstrategie

### ISSUE THREAD

**Issue by tjoekbezoer** [Amsterdam/fixxx-pakjekraam#370]
Indeling wordt **optimistischer**. Als er voldoende plek is, krijgen mensen die willen uitbreiden sneller een 2de plaats, i.p.v. dat dit helemaal aan het eind pas wordt gedaan.

1. Voer telling uit:
    ![IMG_3965](https://user-images.githubusercontent.com/494128/64948652-c63b6580-d877-11e9-9d25-998c524c160d.jpg)
    
   Dit levert het aantal beschikbare plaatsen op voor uitbreiding.
2. Maak een lijst met ondernemers die wil uitbreiden zolang er beschikbare uitbreidingsplaatsen zijn of zolang er geschikte ondernemers zijn.
3. Deel VPH in zonder verplaatsingen. Staat ondernemer in lijst? Breidt uit naar max 2.
4. Deel VPH in met verplaatsingen. Staat ondernemer in lijst? Breidt uit naar max 2.
5. Branche ondernemers idem.
6. Eigen materieel ondernemers idem.
7. Deel sollicitanten in. Staat ondernemer in lijst? Breid gelijk uit naar max 2.
8. Zijn er nog open plekken en ondernemers die verder willen uitbreiden? Pas uitbreiding o.b.v. iteratie toe zoals nu reeds gebeurd.

**Comment by evaleffef** [comment]
Volgorde van indeling branche, eigen materiaal/verkoopinrichting en bakplek #423

**Comment by tjoekbezoer** [comment]
Er moeten nog wat tests geschreven worden, maar vernieuwde indelingsstrategie is geïmplementeerd. De oorspronkelijke uitleg hierboven is niet geheel nauwkeurig met de huidige situatie:

![IMG_C20D2988AEE1-1](https://user-images.githubusercontent.com/494128/66336538-90047980-e93d-11e9-8408-0bcdc656dc60.jpeg)

Voorgaand werd de `MIN` telling als leidraad gebruikt. Dit is gewijzigd naar de `OPTIM` telling. Indien er genoeg marktplaatsen zijn om deze telling te bevatten krijgt iedereen het aantal plaatsen zoals omschreven in de `OPTIM` kolom. Past deze telling niet in het aantal marktplaatsen, dan wordt het toewijzen op de oude manier gedaan, waarna er een aantal uitbreidingsrondes zijn die o.b.v. anciënniteit een uitbreiding aan ondernemers toekent.

De nieuwe strategie wordt de *optimistische methode* genoemd, het origineel de *conservatieve methode*.

**Comment by tjoekbezoer** [comment]
Staat op master, en komt dus met 15 minuten op de staging te staan.

**Comment by tjoekbezoer** [comment]
Heropend omdat het toewijzen van 2 plaatsen nog niet naar behoeven functioneert. In de conservatieve strategie krijgen ondernemers eerst 1 plaats toegekend, waarna ze kunnen uitbreiden naar twee plaatsen.

Gewenst is dat de hoogste anciënniteit als eerste een tweede plaats krijgen, maar in de huidige situatie gebeurd dat niet; de aangelegen plaatsen zijn al bezet door andere ondernemers. Dit betekent eigenlijk dat alleen de laatste ondernemer in een rij kan uitbreiden.

De conservatieve strategie moet aangepast worden zodat alle ondernemers die kúnnen uitbreiden dat gelijk kunnen doen.

**Comment by tjoekbezoer** [comment]
Probleem is opgelost. Nieuwe versie zo online op acceptatie.
