### ISSUE TITLE
Bij kiezen één voorkeursplaats, meerdere plaatsen toekennen

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#371]
In de interface kiest een ondernemer die minimaal 2 plaatsen wil één plaatsnummer. Hij/zij gaat er vanuit dat een aangrenzende vrije plaats 'automatisch' toegekend wordt door de berekening.

Dit geldt ook voor een ondernemer die minimaal 3 plaatsen wil en 2 aangrenzende voorkeuren heeft opgegeven. Enzovoorts...

## Flexibel indelen sollicitanten

In de plaats voorkeuren bij een sollicitant staat onderaan:

![image](https://user-images.githubusercontent.com/39556722/65027348-7a052980-d93a-11e9-9192-e8b9ff89ed49.png)

### Verwacht gedrag

Ondernemer met 2 plaatsen kiest voorkeur 4. Dit kan mogelijk resulteren in plaats 3 & 4, of 4 & 5. Als deze opties niet beschikbaar zijn:

**a. vinkje uit:** wordt de ondernemer afgewezen.

**b. vinkje aan:** wordt de ondernemer ingedeeld op 2 andere beschikbare plaatsen, los van voorkeur.

## Flexibel indelen VPH

In de plaats voorkeuren bij een VPH staat onderaan:

![image](https://user-images.githubusercontent.com/39556722/65027776-3a8b0d00-d93b-11e9-81dd-fa42737544bf.png)

### Verwacht gedrag

Ondernemer met 2 plaatsen (plaats 1 en 2) wil liever 3 plaatsen en kiest voorkeur 4. Dit kan mogelijk resulteren in 2, 3 & 4 of 3, 4 & 5 of 4, 5 & 6.  Als deze opties niet beschikbaar zijn:

**a. vinkje uit:** ondernemer kan niet vergroten naar 3 plaatsen en wordt ingedeeld op 1 en 2.

**b. vinkje aan:** de ondernemer wordt ingedeeld op 3 andere beschikbare plaatsen, los van voorkeur.

#### Aanname

We sluiten hierbij dus uit dat een VPH liever flexibel wil worden ingedeeld op een willekeurige plaats dan op zijn eigen vaste plaatsen (met zelfde aantal kramen/zonder vergroten).

**Comment by tjoekbezoer** [comment]
Voor sollicitanten is het duidelijk.

Voor VPH geeft het vinkje niet de realiteit weer. Zie afbeelding voor een voorbeeld:

![IMG_08C64B2DA9C1-1](https://user-images.githubusercontent.com/494128/65033740-f4877680-d945-11e9-9f82-1aea2bd89e69.jpeg)

Dit is een ondernemer met vaste plaatsen 1 en 2. Hij heeft een verplaatsingsvoorkeur opgegeven naar 3 en 4, en aangegeven dat hij graag 3 plaatsen wil. Omdat verplaatsen en uitbreiden losse gebeurtenissen zijn die niet na elkaar plaatsvinden wordt de ondernemer eerst naar 3 en 4 verplaatst (indien mogelijk). Op een later moment krijgt hij mogelijk een derde plek erbij. Er zijn dus 3 scenario's te identificeren: **worst case** waarbij hij blijft staan, **medium case** waarbij hij enkel verplaatst wordt, en **best case** waarbij hij ook de derde plek erbij krijgt.

Het vinkje suggereert dat een ondernemer **medium case** kan voorkomen. Dit is echter met de huidige aanpak van de berekening niet mogelijk — het is in feite een stoelendans waarbij hij al verplaatst is voordat hij weet of hij kan uitbreiden. Kan hij niet uitbreiden, en wil hij liever terug naar 1 en 2, dan bestaat de kans dat deze plaatsen reeds vergeven zijn.

**Mogelijke oplossingen:**

1. Vinkje verbergen voor VPH.
2. VPH laten uitbreiden tot hun maximaal aantal gewenste kramen, voordat niet-VPH worden ingedeeld.
3. Huidige berekening vervangen voor een algoritme dat niet op basis van een stoelendans principe werkt ([Linear programming](https://en.wikipedia.org/wiki/Linear_programming))

**Comment by tjoekbezoer** [comment]
Besloten is voor nu flexibel indelen voor VPH te verbergen, omdat de belofte die momenteel in de interface staat niet waar gemaakt kan worden (zie uitleg hierboven).

Dit betekent dat een VPH afgewezen wordt als de vaste plaatsen niet beschikbaar zijn en er ook geen voorkeursplaatsen beschikbaar zijn.

Wat dit ticket implementeert is het verplaatsen naar meerdere plaatsen, ook al heeft de ondernemer slechts één voorkeur opgegeven. Een aantal voorbeelden:

1. VPH met plaatsen 1,2 heeft voorkeur 3. Plaats 3 is vrij --> verplaatsing naar 2,3.
2. VPH met plaatsen 1,2 heeft voorkeur 3. Plaats 3 is niet vrij --> blijft staan.
3. VPH met plaatsen 1,2 heeft voorkeur 3,4. Plaats 3 en 4 zijn vrij --> verplaatsing naar 3,4.
4. VPH met plaatsen 1,2 heeft voorkeur 3,4. Plaats 3 is niet vrij --> verplaatsing naar 4,5.
3. VPH met plaatsen 1,2 heeft voorkeur 3,4. Plaats 4 is niet vrij --> verplaatsing naar 2,3.

**Comment by tjoekbezoer** [comment]
**Wijzigingen in de tests voor dit issue**

Uitzetten van willekeurig indelen voor VPH:
https://github.com/Amsterdam/fixxx-pakjekraam/blob/e479d8999a51539d1984146a1bd495b403fbf41f/src/indeling.test.js#L212-L230

Uitbreiding van het testen van verplaatsen van VPH. Dit test zowel verplaatsing met één en meerdere voorkeuren (zie ook comment hierboven):
https://github.com/Amsterdam/fixxx-pakjekraam/blob/e479d8999a51539d1984146a1bd495b403fbf41f/src/indeling.test.js#L388-L495

**Comment by tjoekbezoer** [comment]
@evaleffef De comment beschrijft het inderdaad verkeerd, maar de test zelf staat goed. In dit scenario moet hij echter niet blijven staan, maar naar 2,3 gaan.

**Comment by evaleffef** [comment]
ah ja, dat is natuurlijk ook nog een mogelijkheid, ik zie het idd
