### ISSUE TITLE
Logica uitslag plaatsen uit dashboard in markt detail overzicht terug laten komen. (9 tot 12 - 12 tot 5).

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#378]
## Testen
Als het op volgende links hetzelfde werkt gaat alles goed:
https://acc.pakjekraam.amsterdam.nl/markt-detail/20?eggie=true
https://acc.pakjekraam.amsterdam.nl/dashboard?eggie=true

**Comment by evaleffef** [comment]
Check tussen 17.00 en 21.00 uur (namelijk om 20.10 uur) 
Ondernemer is aangemeld voor morgen. Er is nu niets te zien.

![image](https://user-images.githubusercontent.com/39556722/65174164-a317de00-da50-11e9-97cd-4ced9aac95b6.png)
