### ISSUE TITLE
Activeren met . onmogelijk maken

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#418]
Komt voor uit #341 

Tijdens het activeren de punt uit het registratienummer verwijderen, zodat nieuwe registraties alleen zonder punt in Kies je kraam & KeyCloack bestaan.

## Hiermee voorkomen we
- Verwarring onder ondernemers in de toekomst mbt de gebruikersnaam
- Problemen in het matchen van data in onze applicatie

## Wijzingen
- Er voor gezorgd dat er op /activeren een foutmelding  wordt weergegeven als er geen activatie-code is ingevoerd. Melding is: 'U heeft geen activatie-code ingevoerd.' Dit omdat het mogelijk was om door te gaan naar registreren met enkel een registratienummer (vreemde bug).
- Er voor gezorgd dat het formulier bounced en de volgende melding weergeeft: 'Het ingevoerde registratienummer mag geen punt bevatten.' Als het registratienummer op het formulier op https://acc.pakjekraam.amsterdam.nl/activeren een punt bevat.
- Extra tekst toegevoegd bij het registratienummer: 'Hier vult u uw registratienummer in zonder punt.'

## Testen
Bovenstaande wijzigingen testen op: https://acc.pakjekraam.amsterdam.nl/activeren

**Comment by evaleffef** [comment]
✅ Getest!

![image](https://user-images.githubusercontent.com/39556722/66022632-d9dd0200-e4ee-11e9-941d-2e1add8d8d65.png)
