### ISSUE TITLE
Voor match in e-mail script registratienummer cleanen van punt

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#421]
Komt voort uit #341 

In src/mailing-list.tsx wil je er voor zorgen dat overal waar het erkenningsnummer wordt gebruikt, deze zonder punt is.

**Comment by evaleffef** [comment]
Gecontroleerd op https://github.com/Amsterdam/fixxx-pakjekraam/blob/master/src/mailing-list.tsx#L59
