### ISSUE TITLE
Volgorde van indeling branche, eigen materiaal/verkoopinrichting en bakplek

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#423]
De markt gaat zorgen dat aantal specifieke plaatsen aangewezen als bakplaatsen en dat betekent dus dat ALLEEN op die plaatsen gebakken mag worden!

Er zijn dan straks 5 mogelijkheden voor een plek:

- Bakplek* met een branche (die ook bakt, bijvoorbeeld patat);
- Bakplek*
- Eigen materiaal/Verkoopinrichting (EVI);
- Brancheplek, bijvoorbeeld kaas-zuivel;
- Geen speciale eigenschappen (gewone plek).

*Een bakplek betekent dat er op die plek gebakken mag worden én er mag met eigen materiaal (EVI) gestaan worden. Het bakken heeft hierbij voorrang. 

De stappen van de toewijzing zijn:
- Bakplek met branche: eerst zelfde branche, dan bak, dan EVI , geen EVI dan bij de indeling vergeven aan een kraamhouder;
- Bakplek: eerst bak dan EVI , geen EVI dan bij de indeling vergeven aan een kraamhouder;
- EVI - geen EVI dan vergeven bij de indeling aan een kraamhouder;
- Brancheplek - eerst zelfde branche dan EVI , geen EVI dan bij de indeling vergeven aan een kraamhouder.

Indelingsbesluit Plein '40-'45 volgt deze week.

**Comment by tjoekbezoer** [comment]
@evaleffef

### Vraag 1

> 1. Bakplek*
> 2. Bakplek* met een branche (die ook bakt, bijvoorbeeld patat);

Dit wordt als twee losse stappen gezien, maar hier zit geen onderscheid in neem ik aan?

### Vraag 2

Als er niet genoeg mensen zijn die willen bakken, dan kunnen mensen met EVI op die plekken terecht? Met andere woorden, een bakplaats is ook altijd geschikt als EVI plaats?

### Conclusie

Dan krijg je uiteindelijk:

1. Mensen die willen bakken op een bakplek (en ook enkel daar).
2. Mensen met EVI op een EVI plek (en ook enkel daar).
3. Mensen met branche `X` op een plaats met branche `X` (indien een verplichte branch enkel daar, anders mag elders ook).

Voor alle 3 de stappen geldt: als er niet genoeg geschikte kandidaten zijn mogen de plekken vergeven worden aan 'minder geschikte' kandidaten. (Bak <- EVI <- Branche <- SOLL)

**Comment by tjoekbezoer** [comment]
Problemen zijn opgelost, nieuwe versie staat zo op acceptatie.
