### ISSUE TITLE
Als een marktmeester de plaatsvoorkeuren opent, initiële vinkje per vph/sol

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#429]
Als een marktmeester de plaatsvoorkeuren opent en er zijn nog geen voorkeuren in de database moet:
- bij een sollicitant anywhere aan staan
- en bij een vph anywhere uit staan

## Testen
- Aanvullen

**Comment by evaleffef** [comment]
Lastig in ACC of PROD te testen omdat er geen nieuwe ondernemers zijn, dus de initiële situatie niet nagebootst kan worden. Lokaal wel getest.
