### ISSUE TITLE
Laat het zien in een indeling als de ondernemer zich heeft afgemeld

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#455]

**Comment by evaleffef** [comment]
Over welke plekken/lijsten gaat dit precies?

**Comment by evaleffef** [comment]
✅ Getest in de volgende lijsten:
https://acc.kiesjekraam.amsterdam.nl/markt/20/2019-10-18/indelingslijst/
https://acc.kiesjekraam.amsterdam.nl/markt/20/2019-10-18/concept-indelingslijst/
https://acc.kiesjekraam.amsterdam.nl/markt/20/2019-10-18/indelingslijst/
