### ISSUE TITLE
A-lijst ondernemers gaan voor andere ondernemers

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#462]
Alle marktondernemers op de A-lijst gaan op vrijdag en zaterdag voor op marktondernemers van de B-lijst.
Dus als er een EVI op de B-lijst staat gaat die NIET voor op een niet EVI-marktondernemer op de A-lijst.

Volgorde van branche -> bak  -> EVI waarbij ook hier eerst iedereen op de A-lijst wordt beoordeeld en dan pas de mensen op de B-lijst.
 
Dus de branche, EVI en bakplaats  is ondergeschikt aan de A- en de B-lijst.

**Comment by tjoekbezoer** [comment]
> Volgorde van branche -> bak -> EVI waarbij […]

Ik neem aan dat je bedoelt `bak -> EVI -> branche`?

**Comment by evaleffef** [comment]
Nee, eigenlijk niet. Het is `bak branche -> bak -> EVI -> gewone plek`.

Een plek heeft of een bak branche (bijv. patat) en is een bakplaats. Of het is geen bakplaats, maar een 'gewone' brancheplaats, zoals bijv. Kaas Zuivel.

**Comment by evaleffef** [comment]
Volgorde van indeling van ondernemers zou moeten zijn:
1. VPH's (zonder) op hun eigen plaats;
2. VPH's (met) verplaatsing;
3. Bak op A-lijst;
4. Bak op B-lijst;
5. EVI op A-lijst;
6. EVI op B-lijst;
7. Branche op A-lijst;
8. Branche op B-lijst;
9. Overige op A-lijst;
10. Overige op B-lijst.

Maarrr... logischer is als wij in de berekening hanteren:
1. VPH's (zonder) op hun eigen plaats;
2. Bak + Branche VPH
3. Bak + Branche op A-lijst
4. Bak + Branche op B-lijst;
5. Bak VPH
6. Bak op A-lijst
7. Bak op B-lijst;
8. EVI VPH;
9. EVI op A-lijst;
10. EVI op B-lijst;
11. Branche VPH;
12. Branche op A-lijst;
13. Branche op B-lijst;
14. Overige op A-lijst;
15. Overige op B-lijst.

**Comment by evaleffef** [comment]
@tjoekbezoer wil jij de link naar de tests hier nog bij zetten?

**Comment by tjoekbezoer** [comment]
Maar natuurlijk:

https://github.com/Amsterdam/fixxx-pakjekraam/blob/af61d1995149777fac20593c3d2e131ef17e1d76/src/indeling.test.js#L129-L230
