### ISSUE TITLE
VPH verschuift terwijl hij wil uitbereiden

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#465]
In de indeling van vandaag, dinsdag 15 oktober https://kiesjekraam.amsterdam.nl/markt/20/2019-10-15/indeling/ is te zien dat de VPH op plaats 60,61, 62 wordt verschoven naar 62, 63, 64.

Technisch klopt dit denk ik, want hij heeft voorkeuren 63 en 64 ingevuld, waarmee hij aangeeft liever daar te willen gaan staan. Ik vraag me af of dit de bedoeling is, ik laat dit marktmeesters navragen.

**Comment by tjoekbezoer** [comment]
als ze willen uitbreiden zal hun `maximum` aangepast moeten worden naar een getal groter dan het aantal plaatsen dat ze hebben. Ik weet dat dit in de interface nu anders heet, maar intern zijn de parameters nog steeds `minimum` en `maximum`.

**Comment by evaleffef** [comment]
Dit is nu geen issue: we kiezen er nu voor dat een VPH kan of verplaatsen, of vergroten. 
-> vult hij voorkeuren in, dan gaan we er vanuit dat hij wil verplaatsen;
-> vult hij extra plaatsen in, dan gaan we er vanuit dat hij wil vergroten (op de eigen plek)
-> vult hij beide in dan is de uitkomst onvoorspelbaar.

Dit is wat op dit moment extra gecommuniceerd wordt aan de ondernemers.

**Comment by tjoekbezoer** [comment]
> -> vult hij beide in dan is de uitkomst onvoorspelbaar.

@evaleffef De uitslag is niet onvoorspelbaar, alleen de uitleg is wat lang :)

1. Als er voorkeuren opgegeven zijn (die niet de eigen vaste plaatsen zijn) zal het systeem altijd proberen naar die plaatsen te verplaatsen.
2. Is er via de voorkeuren aangegeven dat ze willen vergroten, dan zal het systeem ook dat proberen:
    2.1. Als ze 1 plaats hebben en willen vergroten naar 2 zal dit gelijk gebeuren. _Dit is "verplaats mij enkel als ik kan uitbreiden"_.
    2.2 Als ze meerdere plaatsen hebben en willen vergroten zal het systeem proberen uitbreiden nadat iedereen is ingedeeld. _Dit is "verplaats mij sowieso, en probeer uit te breiden als het kan"_.
