### ISSUE TITLE
Log van indeling

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#492]
Graag eerst _minimal_ oppakken.

Dus waarschijnlijk vooral loggen welke instellingen er waren op het moment van de indeling.

Daarvoor is deze issue: **Opslaan voorkeuren op moment van indeling #586**

### Documentatie
Noteren waar logbestanden te vinden zijn, en hoe ze gestructureerd zijn... hoe werkt je er ermee https://github.com/Amsterdam/fixxx-pakjekraam/wiki/Berekening

**Comment by evaleffef** [comment]
Vandaag 05/12/2019 besproken tijdens de demo: Marjolein wil geen uitgebreide log nu.

**Comment by tjoekbezoer** [comment]
Het loggen van de input van het algoritme is voltooid, en te vinden in de `log` tabel in de database.
