### ISSUE TITLE
Teksten in activatie/registratie schermen aanpassen

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#502]
De copy in de activatie/registratie schermen is niet uniform nu.

## Registreren
In het registreren scherm (na activatie) https://kiesjekraam.amsterdam.nl/registreren

Titel: `Stel uw wachtwoord in`
Opmerking boven formulier: `Bedenk en onthoud een wachtwoord (tenminste 8 karakters).`
Wachtwoordveld 01: `Vul uw zelfbedachte wachtwoord in:`
Wachtwoordveld 02: `Herhaal het wachtwoord:`
E-mail: `Uw e-mailadres:`

## Welkom
In het welkom scherm (na registratie) https://kiesjekraam.amsterdam.nl/welkom

`U kunt nu inloggen met uw registratienummer en wachtwoord.`

**Comment by evaleffef** [comment]
De copy in de activatie/registratie schermen is niet uniform nu.

In het registreren scherm (na activatie) https://kiesjekraam.amsterdam.nl/registreren

**Comment by Carlio75** [comment]
Sluit issue na overleg met markt, geen prio.
