### ISSUE TITLE
40 - 45 draait ook als er geen markt is. In de berekening kijken of de markt wel open is

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#504]
Berekening ook NIET draaien als markt is `enabled = false`, of als markt is in fase `voorbereiding` of `activatie`.

LET OP: op zondag draait cronjob, omdat er op maandag geen markt is, draait ie de berekening toch! 
Zie bijvoorbeeld: https://kiesjekraam.amsterdam.nl/markt/20/2019-11-04/indeling/ = maandag!

Maarrr... de indeling voor dinsdag bestaat ook al!

## Aanpassingen
Indelingsscript aangepast. Let wel, src/allocation.ts. Op dit moment is degene die draait src/allocation.js vanwege struggles met de cronjob (https://datapunt.atlassian.net/browse/BAS-2573).
- De indeling draait nu alleen als de markt fase 'live' of 'wenperiode' heeft.
- De indeling draait alleen als morgen binnen de marktDagen van makkelijke markt valt.

**Comment by evaleffef** [comment]
Berekening ook NIET draaien als markt is `enabled = false`, of als markt is in fase `voorbereiding` of `activatie`.
