### ISSUE TITLE
🐛 Sommige ondernemers worden niet ingedeeld, andere met minder goed nummer wel

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#532]
Op maandag 04/11 rond 13.00 uur een indeling berekening gedraaid op ACC.
Uitslag: https://acc.kiesjekraam.amsterdam.nl/markt/20/2019-11-05/indeling/

Er zijn twee ondernemers die niet worden ingedeeld, dat kun je terugzien op deze lijst:
https://acc.pakjekraam.amsterdam.nl/markt/20/2019-11-05/voorrangslijst/

![image](https://user-images.githubusercontent.com/39556722/68122112-e697b000-ff09-11e9-9eaf-794714f85f9f.png)

### Andere ondernemers met een slechter nummer, zijn wel ingedeeld met 2 plaatsen.

![image](https://user-images.githubusercontent.com/39556722/68122605-01b6ef80-ff0b-11e9-9cd6-8c47b6f045ec.png)

![image](https://user-images.githubusercontent.com/39556722/68122513-c3b9cb80-ff0a-11e9-8f23-254f41597f36.png)

![image](https://user-images.githubusercontent.com/39556722/68122327-6160cb00-ff0a-11e9-8c58-30eef483d3f6.png)

### Er zijn nog 3 x 2 aangrenzende plaatsen beschikbaar

![image](https://user-images.githubusercontent.com/39556722/68121865-2611cc80-ff09-11e9-96cb-a32516393909.png)

![image](https://user-images.githubusercontent.com/39556722/68122171-0929c900-ff0a-11e9-8b26-7b92a8572126.png)

![image](https://user-images.githubusercontent.com/39556722/68122361-72114100-ff0a-11e9-9bd7-88e6a749f06a.png)

## Instellingen ondernemers

Alle betreffende ondernemers (ingedeeld en niet ingedeeld) in dit voorbeeld hebben Flexibel indelen (anywhere) AAN staan.

## Data 
@tomootes heeft datadump van deze situatie lokaal en opgeslagen met datum 20191104.

**Comment by evaleffef** [comment]
Dit komt ook vandaag weer voor. De sollicitant met het beste nummer is vandaag niet ingedeeld. Hij heeft normale voorkeuren (die geven geen aanleiding om niet te worden ingedeeld)

**Comment by tjoekbezoer** [comment]
`Ondernemer.getStartSize` gaf onterecht een waarde van 1 terug, waar een SOLL had aangegeven minimaal 2 plaatsen te willen.

In `Indeling.performExpansion` werd dit minimum vervolgens wel gerespecteerd. Op dit punt was echter al bepaald wat de meest geschikte plaats voor deze ondernemer was (o.b.v. voorkeuren). Dit kon betekenen dat uitbreiden niet meer mogelijk was omdat aangelegen plaatsen niet beschikbaar meer waren.
