### ISSUE TITLE
🐛ondernemer met voorkeur 74 en 75 krijgt deze plek niet, ondernemer met minder nummer wel

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#537]
Ondernemer met soll. nummer 4630 heeft als voorkeuren 74, 75 opgegeven. 
Een andere ondernemer met soll. nummer 4666 is op deze plekken ingedeeld.

Ander vergelijkbaar issue: [Ondernemer met hoger nummer, krijgt plek die ondernemer met lager nummer als 1e voorkeur heeft opgegeven #549](https://github.com/Amsterdam/fixxx-pakjekraam/issues/549)

**Comment by tjoekbezoer** [comment]
@evaleffef Welke marktdag was dit?

**Comment by evaleffef** [comment]
@tjoekbezoer dit was woensdag 6 november https://kiesjekraam.amsterdam.nl/markt/20/2019-11-06/indeling/

**Comment by tjoekbezoer** [comment]
- Deze ondernemer had op het moment van indelen geen branche ingevuld, en komt daarmee dus onderaan de indelingslijst te staan.
- Het lijkt erop dat deze ondernemer zich op die dag niet op aanwezig heeft gezet; ik vind geen aanmelding en de ondernemer lijkt niet te zijn ingedeeld. Op de live wel, dus dit zal later aangepast zijn?

Ik heb hier momenteel geen betrouwbare data voor om een bug te reproduceren.
