### ISSUE TITLE
🐛ondernemer heeft bakplekken als eerste ingevuld als voorkeuren, deze zijn vrij, maar daar is hij niet ingedeeld

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#538]
Ondernemer heeft ingevuld 113, 114, 115, 116, 117 en 118 als voorkeuren. 

Dit zijn plaatsen met bak en EVI eigenschap. Maar deze plaatsen zijn vrij, toch wordt de ondernemer niet ingedeeld.

**Comment by tjoekbezoer** [comment]
Welke ondernemer? Welke marktdag?

**Comment by evaleffef** [comment]
het was woensdag 6 november, maar welke ondernemer het was kan ik niet meer terughalen

**Comment by tjoekbezoer** [comment]
Gezien de specifieke situatie m.b.t. de voorkeuren had ik genoeg data om de situatie te beoordelen:

- Er zijn maar twee ondernemers met specifieke voorkeuren voor bovengenoemde plaatsen.
- Alle voorkeuren zijn plaatsen voor EVI en/of bakken.
- Beide ondernemers hebben geen EVI en bakken niet.
- Al deze plekken worden door EVI/bak ondernemers bezet, behalve 115 en 116.
- Op deze plek staat een sollicitant met een lager sollicitatieNummer die flexibel indelen heeft aanstaan.

Het huidige gedrag van de berekening is dat iemand die flexibel ingedeeld wilt worden op de eerst beschikbare plaats wordt ingedeeld. Er wordt geen rekening gehouden met voorkeuren van sollicitanten die nog volgen. Voor deze kwestie heb ik issue #556 aangemaakt.
