### ISSUE TITLE
🐛 Emails lijken niet aan te komen

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#542]
Gisteren, donderdag 6 november zijn we erachter gekomen dat deze ondernemers geen indeling mail hebben gekregen (uitslag indeling 6 november)

- 2007083001
- 2018013101
- 2014060401

Ondernemer 2016081701 kreeg wél e-mail!

### Bevindingen
In het mail script gebeurt er niks raars. Door het lijstje heen gelopen en van alle drie genoemde erkenningsnummers krijgen we gewoon netjes een emailadres van Keycloack. De mail() functie daarna ziet er ook goed uit. 

Met @evaleffef afgesproken dat we wachten tot we toegang hebben tot Sendgrid en daarna kijken of we daar kunnen ontdekken wat er mis gaat.

## Bevindingen, tweede keer
```
process.exit(0);
```
Bovenstaande code zorgt er misschien voor dat het proces wordt afgepakt voor de mails allemaal zijn verstuurd. Dit morgen refactoren en daarna op ACC zetten. Ook bij datapunt vragen of ze de credentials op ACC willen toevoegen.

## Wijzigingen
- De nieuwe parameters (telefoonnummer/ fase) uit MM werkend gemaakt in het mail script.
- Aan de hand van de omgeving (acc/dev) stuurt hij nu testmails naar tomootes@gmail.come en eva@tiltshift.nl. Op productie gaat de mail naar de ondernemer.
- Hij doet nu ```process.exit(0);``` pas aan het einde. Waardoor als het goed is alle mails worden verstuurd.

**Comment by evaleffef** [comment]
Vandaag melding via de marktbeheerder dat er ondernemers zijn die aangeven geen e-mail ontvangen te hebben.

Er zijn 52 toewijzingen in de indeling https://kiesjekraam.amsterdam.nl/markt/20/2019-11-15/indeling/, maar er zijn 30 mails verstuurd volgens SendGrid https://app.sendgrid.com/statistics

**Comment by evaleffef** [comment]
Zaterdag 16 november 85 toewijzingen, 65 mails verstuurd

**Comment by tomootes** [comment]
@evaleffef ik heb na alle perikelen met Datapunt de nieuwe opzet nogmaals getest met extra logging. Conclusie: mijn code die naar DEV/ACC keek werkte niet goed. Dit heb ik aangepast en nu werkt het zoals verwacht. 

Dus, op ACC krijgen wij allebei een mailtje. op PROD de ondernemer. Als je wilt testen of de job op ACC werkt kan je een account met erkenningsnummer van een ondernemer aanmaken in Keycloack met je eigen emailadres, dan wordt het account gevonden en wordt er een mail verstuurd.
