### ISSUE TITLE
Ondernemer wordt ingedeeld op andere plaats dan zijn beschikbare voorkeuren

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#545]
Vandaag, donderdag 7 november, is er een ondernemer (4941) die een heleboel voorkeuren ingevuld heeft. 

Hij is ingedeeld met 1 plaats, op een plaats die NIET in zijn voorkeuren voorkomt.

Indeling: https://kiesjekraam.amsterdam.nl/markt/20/2019-11-07/indeling/

De eerste 8 zijn niet beschikbaar, de 9e (44) wel. 
Hij wil 1 plaats + 1.
Hij heeft flexibel indelen aan staan.

Hij wordt niet op deze plaats ingedeeld, maar op **plaats 38**. 

Plaatsen waarop hij o.a. had kunnen worden ingedeeld (vrij gebleven in de indeling):  44 en 45, 140 en 141, 94, 95 en 96, 57 en 58.

Op plaats 40 is een andere ondernemer ingedeeld met een hoger nummer (5000)

**Comment by tjoekbezoer** [comment]
Opgelost door voorgaande bugfixes. Deze ondernemer krijgt met de huidige versie van de berekening op dinsdag 7 november plaatsen 64 en 65. Deze plekken komen voor in hun voorkeuren.
