### ISSUE TITLE
Flexibel indelen VPH vinkje standaard uit in interface

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#548]
Als je als marktmeester bij een ondernemer naar `/voorkeuren/20/` gaat staat het vinkje bij Flexibel indelen standaard aan.

Risico is dat een marktmeester dit niet opmerkt en dit mee-opslaat bij het opslaan van andere wijzigingen.

**Comment by tomootes** [comment]
@evaleffef ik kan dit niet reproduceren. de huidige situatie is als volgt:
- Als je bent ingelogd als VPH gaat deze standaard op false.
- Als marktmeester zie je de status van het vinkje zoals in de DB, dus true of false. Maar hier ook initieel uit als het een VPH betreft.
- Als sollicitant kan je hem gewoon aan/uitvinken.
