### ISSUE TITLE
Ondernemer met hoger nummer, krijgt plek die ondernemer met lager nummer als 1e voorkeur heeft opgegeven

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#549]
Op zaterdag zijn alle ondernemers ingedeeld https://kiesjekraam.amsterdam.nl/markt/20/2019-11-09/indeling/

Het gaat om plaats 140, ondernemer 4551 | O Assbai. 

Hij heeft 1 + 1 ingevuld.
Voorkeuren: 114, 115, 97, 98, 91, 92, 116, 101, 102, 89,  90 (etc...)
En flexibel indelen AAN

Hij heeft dus als 1e  voorkeur 114 ingevuld, 115 als 2e.

Zijn 1e voorkeur is niet beschikbaar, daar is een ondernemer die een beter match heeft met die plek (want bakplek). 

115 is zijn 2e voorkeur, daar is nu een ondernemer ingedeeld met een slechter nummer (4582) die heeft 115 als 8e voorkeur opgegeven en Flexibel indelen UIT.

Vermoede is er dat voorkeursplaatsen helemaal niet meer meetellen zodra je flexibel indelen aan hebt staan, is dat zo @tjoekbezoer?

**Comment by tjoekbezoer** [comment]
Wat betreft ondernemer 4551:

- Ze hebben geen branche ingevuld bij de algemene voorkeuren. Ondernemers die hun branche niet hebben ingesteld worden helemaal als laatste behandeld, dus ook na sollicitanten met een hoger nummer die wél een branche hebben ingevuld.
- Plek 115 is voor EVIs — 4551 heeft niet aangegeven een EVI te hebben.
- Deze ondernemer heeft geen voorkeuren ingevoerd op acceptatie. Is het mogelijk dat ze deze voorkeuren pas hebben toegevoegd na de indeling van 2019-11-09?
- In de live omgeving heeft deze ondernemer zijn voorkeuren reeds aangepast; hij wil nog slechts 1 plaats.

Gezien deze onregelmatigheden laat ik deze issue voor nu zitten.
