### ISSUE TITLE
Vaste plaatshouder wil uitbreiden van 1 naar 2, maar krijgt deze uitbreiding niet (andere ondernemer met slechter nummer wel)

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#550]
Ondernemer 4415 op plaats 23 heeft tijdens de indeling van zaterdag 9 november geen +1 gekregen: https://kiesjekraam.amsterdam.nl/markt/20/2019-11-09/indeling/

Dit is wel juist ingevuld in zijn voorkeuren 1 + 1. 

Een andere ondernemer, de sollicitant 4535 heeft wel 2 plaatsen gekregen. Hij heeft als voorkeuren (minstens) 2 plaatsen ingevuld.

**Comment by tjoekbezoer** [comment]
VPH 4415 heeft een eigen verkoopinrichting. In de marktdefinitie zie ik dat zijn eigen plaats niet als zodanig is gedefinieerd — dat deze plaats toch wordt toegekend is denk ik het juiste gedrag van de berekening.

Dat deze ondernemer niet kan uitbreiden is logisch; plaats 22 is ook niet geschikt voor een eigen verkoopinrichting, net als plaats 24. Daarnaast zit er tussen 23 en 24 een obstakel, wat uitbreiding naar die plaats sowieso onmogelijk maakt.

**Comment by evaleffef** [comment]
@tjoekbezoer ja ik denk dat je gelijk hebt. Ik controleer normaal gesproken dit soort dingen eerst zelf, dat heb ik hier kennelijk niet gedaan, excuus!
Ik ga dit doorgeven aan de marktmeesters, die moeten zorgen dat deze ondernemer de juiste instellingen gaat krijgen, want volgens mij bakt hij helemaal niet
