### ISSUE TITLE
Flexibel indelen moet rekening houden met de voorkeuren van navolgende ondernemers

### ISSUE THREAD

**Issue by tjoekbezoer** [Amsterdam/fixxx-pakjekraam#556]
Momenteel is het zo dat een sollicitant die flexibel ingedeeld wilt worden op de eerst beschikbare marktplaats wordt ingedeeld, ook al zijn er sollicitanten met een lager sollicitatieNummer die die plaats als voorkeur hebben opgegeven.

Het zou mooi zijn als de berekening hier rekening mee houdt — deze ondernemer heeft geen specifieke voorkeur voor deze plaats, dus hij kan net zo goed op een plaats worden gezet waar andere ondernemers geen voorkeur voor hebben uitgesproken.

@evaleffef Is dit wenselijk?

**Comment by evaleffef** [comment]
ja! dit is anders niet uit te leggen aan de ondernemers. 

Dus even in een voorbeeld:
Een markt heeft 2 plaatsen, plaats 3 en 4. 
ondernemer 1 (beste nummer) heeft geen voorkeuren, flexibel indelen aan;
ondernemer 2 heeft als voorkeur plaats 3 opgegeven.

Dan wil je dat ondernemer 2 plaats 3 krijgt en ondernemer 2 plaats 4.

@tjoekbezoer Klopt het dat het dan niet meer uitmaakt of ondernemer 2 flexibel indelen heeft aan staan?

**Comment by tjoekbezoer** [comment]
Ok duidelijk, dan zal ik dat implementeren.

> Klopt het dat het dan niet meer uitmaakt of ondernemer 2 flexibel indelen heeft aan staan?

In dit voorbeeld hoeft ondernemer 2 flexibel indelen niet aan te hebben staan, maar dat betekent niet dat die instelling op een normale markt minder relevant is geworden.

Met bovenstaande functionaliteit geïmplementeerd wordt de indeling waarschijnlijk als eerlijker ervaren, maar de intentie van flexibel indelen blijft volgens mij ongewijzigd en relevant.

**Comment by evaleffef** [comment]
Ik had een issue al voor deze situatie **Ondernemer zonder voorkeur wordt ingedeeld op plek waar andere ondernemer voorkeur op heeft #536**, volgens mij is dat hetzelfde
