### ISSUE TITLE
🐛Lijsten printen nu met teveel witpagina's

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#560]
Indeling print met te veel witte pagina's: https://kiesjekraam.amsterdam.nl/markt/20/2019-11-14/indeling/

Standaard print ik 2, 5, 6, 7 - 1, 3 en 4 zijn dus wit

**Comment by tomootes** [comment]
@evaleffef ben er even ingedoken. Om dit goed op te lossen ben ik misschien wel een dag bezig. Bespreken of dit het waard is. @print css is niet bepaald een pretje :)

**Comment by evaleffef** [comment]
Dat hoeven we niet te bespreken, er zijn andere dingen die nu meer voorrang hebben.
