### ISSUE TITLE
🐛Ondernemer krijgt voorkeuren niet, andere ondernemer met slechter nummer wel

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#566]
Tijdens de indeling van zaterdag 16 november krijgt een ondernemer 4657 geen plek, hij wordt niet ingedeeld. Zie niet ingedeeld: https://kiesjekraam.amsterdam.nl/markt/20/2019-11-16/voorrangslijst/

Hij heeft een aantal plaatsvoorkeuren en flexibel indelen staat uit.

Als 10e voorkeur heeft hij plaats 75 - 4837 ingedeeld.
Zijn 11e voorkeur, 68, daar is 4666 ingedeeld.
12e voorkeur - 4702 ingedeeld.

Belangrijk detail om te vermelden: in ons systeem heeft hij 2 sollicitaties voor dezelfde markt, dat komt ook zo uit Makkelijke Markt. Dit heeft te maken met deze sollicitatie die in Mercato is gewijzigd, waardoor er een .01 of .02 achter het sollicitatienummer wordt gezet. Dit wordt in Makkelijke Markt niet goed verwerkt (beetje kort door de bocht omschreven, zoiets is het)

![image](https://user-images.githubusercontent.com/39556722/68990722-cc899600-0856-11ea-92a5-420370161786.png)

Deze ondernemer werd vorige week zaterdag ook niet ingedeeld. Hij gaat nu een klacht indienen bij de markt.

**Comment by tjoekbezoer** [comment]
Het feit dat deze ondernemer niet werd ingedeeld werd veroorzaakt door andere voorgaande bugs.

In de huidige versie van de berekening wordt de ondernemer wel ingedeeld, hij krijgt echter 2 plaatsen die niet aaneengesloten zijn (zijn sollicitatienummer staat 2x in de lijst). De berekening filter nu dubbele sollicitatienummmers/erkenningsnummers eruit.

**De aanname hierbij is dat beide items in de lijst identiek zijn**.

In de nieuwe versie van de berekening krijgt deze ondernemer op zaterdag 16 november plaats 75; zijn 10de voorkeur.
