### ISSUE TITLE
Langdurig afwezig zichtbaar maken voor ondernemer

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#570]
Als een ondernemer langdurig is afgemeld door een marktmeester, dan kan hij/zij dit zelf niet zien.

Dit zou als een waarschuwing altijd in beeld moeten staan (alle schermen).

Waarschuwing:
`LET OP: U bent langere tijd afwezig gemeld. Klopt dit niet, neem dan contact op met de marktmeesters via {telefoonnummer}.`

**Comment by tomootes** [comment]
@evaleffef overal een waarschuwing in Knexen wordt erg veel werk. Voor nu heb ik alleen een melding op '/markt-detail/20'.
