### ISSUE TITLE
🐛 Ondernemer werd zaterdag niet ingedeeld, onduidelijk waarom

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#573]
https://kiesjekraam.amsterdam.nl/profile/2012012504 heeft afgelopen zaterdag https://kiesjekraam.amsterdam.nl/markt/20/2019-11-16/indeling/ geen plaats gekregen, zonder dat op dat moment duidelijk was waarom.

Heeft dit te maken met het feit dat hij zijn branche niet heeft ingevuld?

**Comment by tjoekbezoer** [comment]
Controle wijst uit dat dit inderdaad aan het niet instellen van zijn branche lag. Met de nieuwe versie van de berekening wordt deze ondernemer ingedeeld. Met de vorige versie van de berekening wordt deze ondernemer afgewezen.
