### ISSUE TITLE
A-lijst ondernemers uitbreiden, vóór B-ondernemers indelen

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#575]
Vandaag is naar voren gekomen dat de volgorde van indelen op vrijdag en zaterdag niet klopt voor markten waar met een A-B lijst gewerkt wordt.
Namelijk alle ondernemers van de A-lijst dienen te worden ingedeeld + uitgebreid, voordat de B-lijst ondernemers een plek mogen krijgen.

Noodoplossing: B lijst uit input filteren

**Comment by tjoekbezoer** [comment]
Gefixed in commit 6e5583b in de master branche.

De tests voor de A-lijst:

https://github.com/Amsterdam/fixxx-pakjekraam/blob/6e5583bcfd302d3e35a1beb7bbb98673b540114d/src/indeling.test.js#L129-L248
