### ISSUE TITLE
Hacken Security issue 02. #470

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#581]
Testen of het echt is opgelost

**Comment by tomootes** [comment]
Om het te testen heb ik een POST request naar een willekeurig formulier gestuurd. Ik heb de test bij 1 formulier gehouden omdat bij elk formulier de zelfde methode is gebruikt om CSRF af te vangen. In onderstaand screenshot zie je dat het endpoint het request niet accepteert zonder CSRF token.

![Schermafbeelding 2019-11-25 om 11 25 25 (2)](https://user-images.githubusercontent.com/4222167/69532690-a9599780-0f76-11ea-8b9a-dc7808e0e6ad.png)
