### ISSUE TITLE
Geblokkeerde plaats/plaatsen zichtbaar maken voor marktmeesters

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#588]
Als een marktbeheerder een veld, of meerdere velden geblokkeerd heeft, door deze in te vullen in de markt settings in Makkelijke Markt, dan moet dat zichtbaar worden voor marktmeesters.

## Veld in Makkelijke Markt
In de markt settings in Makkelijke Markt is een tekstveld waarin plaatsnamen gezet kunnen worden.

### Zichtbaarheid voor marktmeesters
In markt dashboard voor marktmeesters moet een melding komen.

`Geblokkeerde plaats: 10` of
`Geblokkeerde plaatsen: 10, 140`

## Werkzaamheden
Klaar gezet, kan ungecomment als dit werkt in de berekening

**Comment by tomootes** [comment]
@evaleffef er lijkt nog een bug te zitten in het geblokkeerde plaatsen veld in makkelijke markt. Als ik hier een aantal plaatsen invoer: https://makkelijkemarkt-dashboard.datalabamsterdam.nl/markten/edit/16 en opsla dan is de waarde weer leeg bij het verversen van de pagina. ik ga dit nu bouwen met de aanname dat ik van MM een string krijg met comma seperated values. bv: `15,16,17`
