### ISSUE TITLE
🐛Sollicitant D. Indelen wordt niet ingedeeld op Dappermarkt (concept indeling)

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#593]
Tijdens het testen van de wenperiode op de Dappermarkt is ondernemer D. Indelen aangemeld voor een paar dagen.

Instellingen 1 plaats, geen voorkeuren, flexibel indelen aan.

Bij het draaien van de concept indeling wordt hij niet ingedeeld, terwijl er voldoende plek is (hij is de enige sollicitant)

Hij staat ook op de lijst van ondernemers die niet zijn ingedeeld: https://acc.kiesjekraam.amsterdam.nl/markt/16/2019-11-28/voorrangslijst/

Voorbeeld van concept indeling https://acc.kiesjekraam.amsterdam.nl/markt/16/2019-11-28/concept-indelingslijst/

### Reproduceren
- Dappermarkt moet in Makkelijke markt op fase `wenperiode` staan - LET OP zowel onze ACC als onze PROD omgeving kijken naar dezelfde Makkelijke Markt!
- Ondernemer aanmelden voor een dag;
- Concept indeling van die dag oproepen.

**Comment by tjoekbezoer** [comment]
Ik heb de data van die dag op ACC bekeken. Een aantal observaties die voorkomen dat de indeling goed verloopt:

- Er is een flink aantal ondernemers dat geen juiste status heeft. Mogelijke waardes: `vph`, `vkk` en `soll`. Er zijn 7 ondernemers met status `?`.
- De `indeling.aanmeldingen` property is praktisch leeg; er staan slechts twee ondernemers waarbij de property `attending` op false staat. M.a.w., niemand heeft zich aangemeld. Ik vermoed dat enkel de VPHs worden ingedeeld — voor hen is aanmelden niet verplicht.
- Test ondernemer 'D Indelen' heeft een niet bestaande vaste plaats (`244 TVPL`).

Enkel kijkend naar ondernemer 'D Indelen' geeft: Een status van `?`, een niet bestaande vaste plaats en niet aangemeld voor deze marktdag. Ik zou me eerder zorgen maken als deze ondernemer wél ingedeeld zou worden ;)

**Comment by evaleffef** [comment]
Ai, dat is ongelukkig. De situatie is veranderd inmiddels, waardoor D. Indelen inderdaad een ander type is geworden.
Je kunt op ACC een andere sollicitant nemen en die aanmelden en dan zie je dat die ook niet wordt ingedeeld. Ik heb dit uitgebreid onderzocht en getest, verschillende situaties uitgeprobeerd. De enigen die ingedeeld worden op de Dappermarkt zijn de VPH's

**Comment by evaleffef** [comment]
Overigens zie ik in de concept indeling van morgen (woensdag 07/01) dat er wél sollicitanten worden ingedeeld, dus wellicht is het inmiddels al verholpen.

**Comment by evaleffef** [comment]
Sollicitanten worden nu wel degelijk ingedeeld, issue vervalt
