### ISSUE TITLE
Upgrade connect-pg-simple from 5.0.0 to 6.0.1

### ISSUE THREAD

**Issue by tomootes** [Amsterdam/fixxx-pakjekraam#601]
Gerelateerd aan volgende PR:
https://github.com/Amsterdam/fixxx-pakjekraam/pull/324

Resulteert in deze error:
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Vermeende oplossing: https://stackoverflow.com/questions/54301624/err-http-headers-sent-cannot-set-headers-after-they-are-sent-to-the-client/54301739

**Comment by tjoekbezoer** [comment]
De kwetsbaarheid in v5.0.0 betreft het niet 'escapen' van de tabelnaam die gebruikt wordt om sessiedata in op te slaan. In theorie betekent dit dat een bezoeker van de website de database kan overnemen als deze de mogelijkheid heeft om deze tabelnaam te wijzigen. In de historie van de mensheid is er echter nog nooit een applicatie geweest die het voor haar bezoekers mogelijk maakte om de tabel waarin alle sessies worden opgeslagen te wijzigen, niet in de laatste plaats omdat het nul toegevoegde waarde heeft.

Daar komt nog bij dat wij überhaupt op geen enkele plek in de applicatie deze tabelnaam opgeven — wij maken gebruik van de standaard configuratie. Hierdoor is het praktisch gezien onmogelijk om  een sessietabelnaam op te geven waarmee de database gecompromiteerd wordt.

Aangezien het upgraden van deze module naar v6.0.1 er voor zorgt dat de applicatie niet meer functioneert (zie hierboven), en de oorzaak lijkt te liggen in een concurrency probleem zie ik geen heil in het oplossen hiervan.

Wat mij betreft laten we dit voor wat het is.
