### ISSUE TITLE
Dag blokkeren - zichtbaar in uitslag component

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#608]
Indien een marktdag is geblokkeerd, dan dit ook zichtbaar maken in uitslag component

## Aanleiding
**Dag blokkeren #445**

- [x] Markering niet groen maar oranje
- [x] Tekst: `Geen markt`
- [x] Niet tonen: uitslag (is er waarschijnlijk niet omdat markt indeling niet draait op geblokkeerde dag)
- [x] Niet tonen: geen toewijzing/afwijzing

![image](https://user-images.githubusercontent.com/39556722/70627198-10897400-1c26-11ea-84c7-e946eccfaa05.png)

**Comment by evaleffef** [comment]
Bij nader inzien, beetje gek als er bij morgen staat: er is vandaag geen markt. 
Kunnen we dit aanpassen in `Er is geen markt` of `Er is deze dag geen markt`

**Comment by tomootes** [comment]
@evaleffef opgelost. Als een markt geblokkeerd is zie je nu alleen de tekst `Geen markt`.
