### ISSUE TITLE
VPH krijgt niet eigen plaatsen, maar verschuift

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#619]
Tijdens de indeling van 17-12 wordt een VPH van zijn plaats geduwd door een andere VPH.  Dit zelfde gebeurt in de indeling van 19-12, bij dezelfde ondernemer.

Situatie: de hoek 54 is vrij. Ondernemer A (4482) heeft die als voorkeur opgegeven. Ondernemer B met betere anciënniteit ook. Ondernemer B (3282) wil 2 plaatsen. Hij krijgt 54 en 55. 

Ondernemer A heeft als vaste plaatsen 55 en 56. Hij verschuift naar 56 en 57. Terwijl hij beide plaatsen niet als voorkeur heeft opgegeven.

Indeling van https://kiesjekraam.amsterdam.nl/markt/20/2019-12-17/indeling/

Ondernemer A Aderdouch is van plaats geduwd. Heeft voorkeuren 54, 55, zie: https://kiesjekraam.amsterdam.nl/ondernemer/2008012102/toewijzingen-afwijzingen

Andere ondernemer er naast:
https://kiesjekraam.amsterdam.nl/ondernemer/2001092502/toewijzingen-afwijzingen

### Andere issue
Mogelijk als deze is opgelost is ook **VPH wordt uit indeling geduwd door andere VPH #610** opgelost.

**Comment by tjoekbezoer** [comment]
Voor zeer specifieke situaties als deze is dit probleem opgelost. Als een VPH maar heel weinig voorkeuren heeft opgegeven die zich allemaal in dezelfde marktrij bevinden, is er een reeële kans dat deze VPH een gedeelte van zijn eigen vaste plaatsen nog altijd zal willen, ook al heeft deze VPH aangegeven te willen verplaatsen.

De huidige situatie is dat al zijn vaste plaatsen vogelvrij verklaard zijn; een VPH met hoger anciënniteit zou al zijn plaatsen in kunnen nemen.

In de nieuwe situatie zullen de vaste plaatsen die hij nooit zal verlaten niet beschikbaar komen voor anderen. Dus als een ondernemer als voorkeuren heeft: `1 2* 3*` (Nummers met een ster zijn hun vaste plaatsen), dan zal plaats `2` nooit beschikbaar worden voor anderen. Deze ondernemer wil twee plaatsen en zal dus in elk scenario plaats `2` bezet houden.
