### ISSUE TITLE
Implementeren sollicitant met tijdelijke vaste plaats (Experimentele Zone)

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#623]
Er is een type ondernemer toegevoegd in Mercato en Makkelijke Markt t.b.v. de experimentele zone. 

Namelijk: ondernemers moeten daar een tijdelijke vaste plaats kunnen krijgen, maar zonder dat zij in de facturatie stroom mee gaan.

Onze test account heeft nu dit type sollicitatie voor de Dappermarkt: https://kiesjekraam.amsterdam.nl/markt-detail/16

- hebben een vaste plaats/plaatsen;
- gaan in de berekening mee als VPH (alleen mogen ze nooit verplaatsen, maar dat hoeven wij niet in de bouwen/uit te sluiten);
- zijn standaard **niet aanwezig** (tegenstelling tot VPH's) tenzij ze aangeven dat wel te zijn;
- kunnen niet zelf hun minimum aantal plaatsen instellen (net als VPH's).

**Comment by tjoekbezoer** [comment]
Om dit mogelijk te maken moest het prioriteren van ondernemers in een verplichte branch verbeterd worden. Door een misverstand was dit geïmplementeerd als 'Probeer alle bakkende ondernemers op een bakplek in te delen'. Dit moest zijn 'Probeer alle ondernemers in een verplichte branche op een brancheplek in te delen'.

Tijdens deze verbetering kwamen er nog een paar kleine puntjes naar boven w.b. prioritizering. Deze zijn nu opgelost, wat de weg vrij maakt om de experimentele zone te implementeren.

**Comment by tjoekbezoer** [comment]
Huidige stand van zaken:

- [ ] Hebben een vaste plaats/plaatsen;
- [ ] Gaan in de berekening mee als VPH (alleen mogen ze nooit verplaatsen, maar dat hoeven wij niet in de bouwen/uit te sluiten);
- [ ] Zijn standaard niet aanwezig (tegenstelling tot VPH's) tenzij ze aangeven dat wel te zijn;
- [ ] Kunnen niet zelf hun minimum aantal plaatsen instellen (net als VPH's).
