### ISSUE TITLE
VPH verplaats niet, sollicitant krijgt de plaats

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#624]
Indeling van https://kiesjekraam.amsterdam.nl/markt/20/2019-12-20/indeling/

Gaat om plaats 54. 

deze ondernemer krijgt de plaats: https://kiesjekraam.amsterdam.nl/ondernemer/2015022601/toewijzingen-afwijzingen terwijl deze ondernemer er meer recht op heeft: https://kiesjekraam.amsterdam.nl/ondernemer/2008012102/toewijzingen-afwijzingen

**Comment by tjoekbezoer** [comment]
Als ik nu de instellingen van ondernemer `2008012102` controleer, dan zie ik geen plaatsvoorkeuren staan — plaats 54 is uit de voorkeuren verwijderd. Het is niet te achterhalen of dit op 20 december ook reeds het geval was, maar als ik voorkeur 54 terugplaats en de indeling opnieuw draai wordt deze ondernemer wel op plaats 54 en 55 neergezet.

Aangezien de andere ondernemer een sollicitant is, en het technisch onmogelijk is dat deze sollicitant eerder aan de beurt was om een plaats te kiezen, ga ik er vanuit dat voorkeur 54 reeds verwijderd was voor de indeling van 20 december.

**Comment by evaleffef** [comment]
Zie aanvulling (te veel ondernemers info anders) op Slack
