### ISSUE TITLE
E-mail met marktindeling niet sturen op geblokkeerde dag

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#625]
### Wijzingen
Het emailproces kijkt nu of er in makkelijke markt de property ``kiesJeKraamGeblokkeerdePlaatsen`` is gezet. Als deze gezet is en dit komt overeen met de berekeningsdatum wordt de markt uit de lijst gefilterd.

**Comment by evaleffef** [comment]
@tomootes Kijkt het e-mailscript ook naar https://github.com/Amsterdam/fixxx-pakjekraam/blob/master/config/markt/daysClosed.json, of alleen geblokkeerde plaatsen in Makkelijke Markt?

**Comment by tomootes** [comment]
@evaleffef ja hier wordt naar gekeken. Het script kijkt naar: kiesJeKraamActief, marktDagen, kiesJeKraamGeblokkeerdeData en daysclosed.json.
