### ISSUE TITLE
VPH die wil verplaatsen krijgt een plaats niet, sollicitant wel

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#640]
Tijdens de indeling van donderdag 16 januari https://kiesjekraam.amsterdam.nl/markt/20/2020-01-16/indeling/ wil een vaste plaatshouder (4467) verplaatsen naar plaats 88. Een sollicitant (4566) krijgt de plaats.

**Comment by tjoekbezoer** [comment]
De oorzaak van dit probleem is gevonden: in specifieke situaties is de opgeslagen prioritering van een ondernemer niet correct. Het kan dan voorkomen dat 2 voorkeuren dezelfde prioriteit van `1` hebben gekregen. De berekening weet vervolgens niet welke van de twee belangrijker is en kiest er 1. In het geval hierboven is dat dus de verkeerde.

De oorsprong van dit probleem zit in het formulier waarin de voorkeuren worden opgeslagen. Als een gebruiker een nieuwe voorkeur toevoegt, en daarna gelijk op 'Bewaar' klikt krijgen de onderste twee voorkeuren allebei een prioriteit van `1` (indien er meerdere voorkeuren in de lijst staan natuurlijk).

@tomootes is met een fix bezig.
