### ISSUE TITLE
Aparte lijsten - A/B lijst

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#644]
Apart lijst maken voor A/B lijst met url `A-B-lijst`

In dashboard checken of er een AB lijst is (data makkelijke markt) if ja dan de link tonen.

### Toepassen:
- Laten zien op ABLIJSTDAG
- Laten zien in activatie - wenperiode - live
- Hernoemen naar ab-lijst
- Kijken naar markt.indelingstype

**Comment by tomootes** [comment]
@evaleffef er is nu geen éénduidige manier om uit te vinden of een markt op een bepaalde dag een a/b lijst hanteert. Hier moeten we een oplossing voor vinden. Aan het endpoint vragen gaat niet lukken want als er niemand op de A/B lijst staat krijg je een lege array terug. Op zon moment kan het dan wel een A/B lijst dag zijn.

**Comment by tomootes** [comment]
Met @evaleffef besproken. We gaan uitzoeken of A/B lijsten altijd op dezelfde dag voorkomen. Dan kunnen we uit de voeten met een vinkje in Makkelijke Markt.

**Comment by evaleffef** [comment]
Uitgezocht: ALS er A/B lijsten gebruikt worden op een markt, dan is dat ALTIJD op vrijdag en zaterdag!
