### ISSUE TITLE
Foutmelding bij dubbel aanmelden

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#647]
Tekst in foutmelding bij dubbele aanmelding herhaalt x het aantal dagen dat je dubbel aangemeld bent.

![image](https://user-images.githubusercontent.com/39556722/72876989-1cbe2200-3cf8-11ea-9ec2-d06fa3a3d1e8.png)

**Comment by Carlio75** [comment]
Sluit issue na overleg met markt, geen prio.
