### ISSUE TITLE
Documentatie Berekening

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#654]
@tjoekbezoer wil jij het gedeelte over de Berekening aanvullen?<https://github.com/Amsterdam/fixxx-pakjekraam/wiki/Indeling#berekening>

**Comment by tjoekbezoer** [comment]
@evaleffef Wie is de lezende doelgroep?

**Comment by evaleffef** [comment]
Ik schrijf dit soort dingen altijd met mezelf over 6 maanden in gedachte. De wiki is bedoelt voor mensen die later aan dit project gaan werken, doorontwikkeling, maar ook beheer.
