### ISSUE TITLE
Meer AGF ondernemers ingedeeld dan maximaal aangegeven

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#657]
Zie mail, gaat over Plein 40-45

**Comment by tjoekbezoer** [comment]
Het probleem is gelokaliseerd: De Makkelijke Markt API stuurt de branche waar een ondernemer toe behoort door als string in `ondernemer.voorkeur.brancheId`, terwijl de berekening hier verwacht dat er een array van strings wordt gestuurd in `ondernemer.voorkeur.branches`.

Dit is nooit aan het licht gekomen, omdat in de testsuite ook altijd met een `branches` array is gewerkt. M.a.w. `maximumPlaatsen` heeft nog nooit goed gefunctioneerd.

Ik werk nu aan een oplossing, en loop gelijk na of er nog andere properties zijn die op deze manier niet goed gebruikt worden.

**Comment by tjoekbezoer** [comment]
Het probleem zat in de data input voor de berekening. Branche instellingen worden op twee plaatsen opgeslagen: algemeen en marktspecifiek. In de marktspecifieke instellingen staan zaken als `maximumPlaatsen` en `verplicht`. Deze instellingen werden niet samengevoegd waardoor enkel de algemene brancheinstellingen werden doorgegeven aan de berekening.

**Comment by Carlio75** [comment]
Check of dit alleen van toepassing is op sollicitanten. nu getest door vph te veranderen van branche naar AGF, maar dat triggerde niets. 
Wat is vervelender, als een VPH niet wordt ingedeeld doordat hij van branche switched of houden we vast aan het max aantal kramen per
