### ISSUE TITLE
Nieuw aanwezigheidsformulier (meerdere markten)

### ISSUE THREAD

**Issue by tjoekbezoer** [Amsterdam/fixxx-pakjekraam#658]
Het doel is het instellingen van de aanwezigheid op meerdere markten tegelijk. Met het oorspronkelijke formulier is enkel de aanwezigheid van één markt in te stellen.

* Het bestaande formulier is niet goed herbruikbaar; de kwaliteit van de code is laag en niet goed schaalbaar.
* `routes/market-application.ts` vraag om refactoring om de nieuwe functionaliteit te implementeren (o.a. gewijzigde validatie).
* Zowel de ondernemerspagina als de marktmeesterpagina moet gemaakt worden.

- [x] Nieuwe pagina aanmaken o.b.v. oude ontwerp.
- [x] Input data structureren.
- [x] Basisversie nieuw formulier ontwikkelen inclusief validaties.
- [x] Grafisch ontwerp formulier afronden.

**Comment by tjoekbezoer** [comment]
Ik heb dit ticket eerst afgerond, omdat de wijzigingen in deze branche van invloed zijn op #659.

**Comment by Carlio75** [comment]
Getest: het is mogelijk om meerdere markten te selecteren. Gaat goed op de ondernemers pagina en op de marktmeester pagina. En de wijziging gaat ook goed op de concept indeling.

Wel heb ik een bugje gevonden mbt het tonen van de markten, dat staat in ticket: https://github.com/Amsterdam/fixxx-pakjekraam/issues/665

En er een change om de foutmelding bij te veel markten duidelijker te maken. https://github.com/Amsterdam/fixxx-pakjekraam/issues/666
