### ISSUE TITLE
Nieuwe ondernemer types

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#659]
Binnenkort zal het marktbureau gaan werken met nieuwe namen voor ondernemer types. 
Dit is vooruitlopend op de aangepaste marktverordening.

### De benamingen
- `vpl` Vaste plaatshouders : vaste plaatshouders
- `expf` *<--- nieuw* Expl Zone F : Experimentele zone met factuur – Deze ondernemer staat vaker dan 3 keer op de expl. Zone – heeft wel een vaste plek. Binnen Kies je kraam is deze qua gedrag hetzelfde als `exp`.
- `exp` Expl Zone: Experimentele zone – deze ondernemer staat minder dan 3 keer op de expl zone – heeft wel een vaste plek op de dagen dat hij staat – pint op de markt
- `tvpl` (was `vkk`) TVPL: Tijdelijke vaste plaatshouder met plaats – heeft een vaste plek toegewezen. Zelfde rechten en plichten als vasteplaatshouder
- `tvplz` *<--- nieuw* TVPLZ: Tijdelijke vaste plaatshouder zonder plaats : heeft in het systeem wel een plek. Maar mag daar geen rechten aan ontlenen. Voor de rest zelfde rechten en plichten als vaste plaatshouder. Binnen Kies je kraam: indelen na `vpl` maar zonder meenemen van aangewezen plaats -> indelen op voorkeur en/of flexibel indelen, standaard niet aanwezig, zelf aanmelden (dus eigenlijk indelen en behandelen als sollicitant, maar als groep wel vóór sollicitanten indelen)
- `soll` Sollicitant: sollicitant

Deze types zullen aangemaakt moeten worden in Mercato en zullen verwerkt moeten worden in Makkelijke Markt. Zodra ze beschikbaar zijn in de Makkelijke Markt API zullen deze wijzigingen ook moeten worden doorgevoerd in Kies je kraam.

Deze wijzigingen zijn inmiddels doorgevoerd in Makkelijke Markt. 

Note: de ondernemer met `vkk` bestaat nog wel, naast de `tvpl` omdat het anders historisch niet goed gaat. In theorie hebben we hier niet mee te maken omdat dit type ondernemer vanaf nu niet meer bestaat (zijn allemaal omgezet).

## Werkzaamheden
- zorgen dat zowel `exp` als `expf` ondernemers dezelfde interface en rechten qua indeling krijgen;
- `tvpl` moet ingedeeld worden na de `vpl` en heeft een vaste plaats;
- `tvplz` moet ingedeel worden na de `vpl` (en voor de sollicitanten) en heeft GEEN vaste plaats (ook als deze wel ingevoerd is in Mercato/Makkelijke markt -> plaats nergeren (in interface en berekening) en verder behandelen als sollicitant (maar wel voorrang geven op indeling boven sollicitanten)

**Comment by evaleffef** [comment]
Vraag: aantal plaatsen van `tvplz` aangegeven in Mercato/Makkelijke Markt -> mag dit gewijzigd worden?

**Comment by tjoekbezoer** [comment]
Opmerking: `exp` wordt in ons systeem niet begrenst; hij mag zich meer dan 3 keer aanmelden, ook al is dat feitelijk niet toegestaan. Controle hierop vindt plaats door het marktbureau zelf.

**Comment by evaleffef** [comment]
> Opmerking: `exp` wordt in ons systeem niet begrenst; hij mag zich meer dan 3 keer aanmelden, ook al is dat feitelijk niet toegestaan. Controle hierop vindt plaats door het marktbureau zelf.

Dit heb ik geverifieerd en is correct!

**Comment by evaleffef** [comment]
> Vragen:
> 
> * aantal plaatsen van `tvplz` aangegeven in Mercato/Makkelijke Markt -> mag dit gewijzigd worden?

Nee. Een tvplz staat op de nominatie voor een vaste plaats. Hij/zij heeft een aantal plaatsen toegewezen gekregen (we gebruiken alleen het plaatsnummer niet) -> het kiezen van het aantal plaatsen werkt voor de `tvplz` hetzelfde als voor de vaste plaatshouders (ze kunnen alleen +1 etc doen)

> * hoe werkt anciënniteit tussen `vpl` en `tvplz` bij verplaatsen/indelen?

**Comment by tjoekbezoer** [comment]
> Nee. Een tvplz staat op de nominatie voor een vaste plaats. Hij/zij heeft een aantal plaatsen toegewezen gekregen (we gebruiken alleen het plaatsnummer niet) -> het kiezen van het aantal plaatsen werkt voor de `tvplz` hetzelfde als voor de vaste plaatshouders (ze kunnen alleen +1 etc doen)

Je antwoord is niet duidelijk voor mij. Je zegt eerst dat ze het aantal plaatsen niet mogen wijzigen, maar vervolgens lijk je te zeggen dat ze wel +1 etc mogen doen. Ze mogen dus wél uitbreiden?

**Comment by evaleffef** [comment]
Klopt @tjoekbezoer een ondernemer die in Mercato 2 tijdelijke vaste plaatsen heeft zonder nummer, mag er niet maar één afnemen, of zijn minumum aantal op 3 instellen (zelfde behandelen in de interface als een VPH). 
Hij mag wél +1, +2 of +3 doen.

**Comment by evaleffef** [comment]
Ter verduidelijking: een tvplz ziet, net als een vaste plaatshouder dit in zijn plaatsvoorkeuren scherm: 

![image](https://user-images.githubusercontent.com/39556722/79864298-8920ee00-83d9-11ea-9d90-9579d8c507a4.png)

**Comment by Carlio75** [comment]
Ik kan op acceptatie het nieuwe type tvplz zien. 
<img width="978" alt="Screenshot 2020-05-18 at 13 45 16" src="https://user-images.githubusercontent.com/64955526/82210347-328ecd00-990f-11ea-879e-e0579756018a.png">

**Comment by Carlio75** [comment]
Ticket is niet te testen omdat ik geen andere ondernemerstypes kan aanmaken om regels en views te testen.

**Comment by Carlio75** [comment]
om te testen:
- alle markten en ondernemers in Kies je Kraam doorlopen, bij vraagteken of andere afwijking de ondernemer opzoeken in makkelijke markt.

- ondernemers met vaste plaats moeten terug komen op de indeling. ondernemers met een tijdelijke vaste plaats moeten terug komen in de lijst met sollicitanten (en klopt de naam sollicitanten dan nog).

**Comment by Carlio75** [comment]
Met invoering van de 1,5 meter markt komen de nieuwe ingevoerde ondernemerstypes uit ticket 659 te vervallen.
In de 1,5 meter situatie werkt de gemeente alleen met VPH en SOLL.

Het toevoegen van de nieuwe ondernemerstypes was een wens van voor de 1,5 meter markt en is voor de implementatie van de 1,5 meter markt gebouwd en naar acceptatie gezet.
Met de introductie van de 1,5 meter markt in Mercato zijn de nieuwe ondernemerstypen komen te vervallen.
Gevolg is dat we deze niet meer kunnen testen.

Ticket 675 is een reminder om bij de herintroductie van de nieuwe ondernemerstypes te testen om deze goed zichtbaar zijn op acceptatie en op productie.
https://github.com/Amsterdam/fixxx-pakjekraam/issues/675

**Comment by Carlio75** [comment]
vph en soll zijn zichtbaar op acceptatie, dat zijn in de huidige situatie alle beschikbare rollen
