### ISSUE TITLE
Issue met AGF ondernemers

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#660]
Zie mail van 2 maart.

MVP oplossing
- [x] zorgen dat er niet meer boven de 24 kramen wordt ingedeeld;
- [ ] berekening in berekening (optimistisch/conservatief indelen binnen branche maximalisatie groep)

NOTE: deze problematiek is niet branche AGF specifiek, maar geldt voor gemaximaliseerde braches.

**Comment by evaleffef** [comment]
Melding van Desiree: 
De indeling van plein 40-45 (van zaterdag 21/03) is naar mijn mening niet goed gegaan.
De vaste groente boeren hebben allemaal de extra kraam gekregen die ze hadden gevraagd, maar meerdere sollicitanten met AGF hebben niks gekregen.
Alle sollicitanten stonden op de A lijst (zijn dus geweest afgelopen week). Ik kan niet vinden waar het fout is gegaan.
 
Deze sollicitanten hebben buiten het net gevist:

4756 | soll | Errakli M |   |  
-- | -- | -- | -- | --
4941 | soll | Talagui K |   |  
5000 | soll | Mouzouri A |   |  
5182 | soll | Tallagui M |   |

**Comment by tjoekbezoer** [comment]
De bevindingen van Desiree waren correct; de indeling deed het verkeerd. Dit had 2 oorzaken:

1. Als de hele markt genoeg plek had en optimistisch ingedeeld werd, dan gold dit ook automatisch voor branches die gelimiteerd waren — zoals AGF. De nieuwe versie bekijkt los van de gehele markt of een gelimiteerde branche ook optimistisch ingedeeld mag worden. Dit is de 'markt in markt' toevoeging.
2. Er zat een fout in het laden van de A-lijst in het geheugen. Hierdoor kon de berekening niemand in deze lijst vinden en werden alle sollicitanten onterecht als B-lijst ondernemers behandeld.
