### ISSUE TITLE
Branches per plaats en maximum per markt  zichtbaar maken op marktindeling

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#661]
Er is nu weinig inzicht in branches in de indeling. NIet hoeveel ondernemers van welke branche zijn ingedeeld, maar ook niet welke plaatsen brancheplaatsen zijn (wel dat ze het zijn, maar niet welke branche). 

### Ingedeelde ondernemers in gemaximaliseerde branche

Bijvoorbeeld bij de maximalisatie van AGF kramen op 24, moet de marktmeester handmatig het aantal AGF kramen tellen (omdat hij uit zijn hoofd weet wie dat zijn kan hij dat doen, een ander moet alle ondernemers één voor één nakijken).

Dit is nodig om bij de handmatige indeling + de controlerondes de juiste gegevens te hebben.

#### Wens
- zien hoeveel kramen ingedeeld zijn in een gemaximaliseerde branche;
- zien welke ondernemers dat zijn, in welke verplichte branche.

Dus niet kunnen zien van alle ondernemers in welke branche zij zitten, want dat is niet altijd nodig om te weten en wordt dan juist onduidelijker.

### Brancheplaatsen zijn er op een markt 

Welke plaatsen zijn branche plaatsen en welke branches dan.

Je kunt in de huidige indeling wel zien dát een plaats een brancheplaats is, maar niet welke branche.

![image](https://user-images.githubusercontent.com/39556722/81566887-cd315e00-939b-11ea-8532-bdb4442695ba.png)

#### Wens
- in de indeling kunnen zien welke plaatsen welke branches hebben als eigenschap.

### Data
Deze data is beschikbaar, dus kunnen we zichtbaar maken. 
Vraag is waar en hoe geeft dit de meeste waarde?

Vooral het aantal ingedeelde kramen binnen een gemaximaliseerde branche lijkt belangrijk/handig.

**Comment by Carlio75** [comment]
Door @tjoekbezoer  op Acceptatie gezet
