### ISSUE TITLE
Nieuwe API url Makkelijke Markt

### ISSUE THREAD

**Issue by evaleffef** [Amsterdam/fixxx-pakjekraam#662]
Dave schrijft in Slack:

De nieuwe acceptatieomgeving voor makkelijkemarkt is klaar en draait op onze secure omgeving. De URLs zijn:
https://acc.makkelijkemarkt-dashboard.amsterdam.nl
https://acc.makkelijkemarkt-api.amsterdam.nl
Kunnen jullie testen of de integratie met pakjekraam/kiesjekraam goed werkt?
Voor de functionele testen van makkelijkemarkt heb ik contact met Marieke Grosjean van het marktbureau.

**Comment by evaleffef** [comment]
@tjoekbezoer LET OP: de versie die nu geïnstalleerd is op ACC is niet de meest recente. Kun je tijdelijk weer verwijzen naar onze oude MM omgeving?

**Comment by tjoekbezoer** [comment]
Ik begrijp van Dave dat de MM versie wel degelijk de nieuwste is, maar dat er gebruik wordt gemaakt van test data voor Mercato. Aangezien ik geen wijzigingen kan aanbrengen in de URL voor acceptatie, zou je dit met Dave willen opnemen? Jij weet nl wat je mist en graag wilt zien.
