### ISSUE TITLE
Markt in voorbereiding zichtbaar bij Ondernemer

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#665]
Wat: 
Als je als ondernemer inlogt mag je alleen markten zien (en aanpassen) die op activatie/wenperiode/live staan. Nu zie je echter ook markten die op VOORBEREIDING staan. En deze mag de marktmeester wel zien, maar de ondernemer niet.

Omgeving en rol:
https://acc.kiesjekraam.amsterdam.nl
2015022601

Meer detail:
Ondernemer ziet Plein 40-45 (fase live), Dappermarkt (fase activatie) en Albert Cuyp (fase voorbereiding).

Hij ziet de markten NIET op de Mijn Markten pagina. https://acc.kiesjekraam.amsterdam.nl/dashboard/ --> daar ziet hij plein 40-45 (dat is correct want live) en Dappermarkt (ook correct want activatie).

Maar WEL als je klikt op een markt en daarna op Wijzig aanwezigheid. 
https://acc.kiesjekraam.amsterdam.nl/aanwezigheid/ --> dan ziet hij alle 3 de markten en hij mag Albert Cuyp (want voorbereiding) dus niet zien.

Op het wijzigen aanwezigheid scherm zou hij dus alleen markten NA de voorbereidingsfase moeten zien. 
https://github.com/Amsterdam/fixxx-pakjekraam/wiki/Markt-fases#fase

Ik denk dat de check op fase niet goed is meegenomen. In de view van de marktmeester gaat het wel goed en worden er bij de ondernemer alle markten getoond die op Zichtbaar staan.

**Comment by tjoekbezoer** [comment]
> Als je als ondernemer inlogt mag je alleen markten zien (en aanpassen) die op activatie/wenperiode/live staan.

Voor de duidelijkheid: je bedoelt 'wenperiode/live' neem ik aan?

**Comment by Carlio75** [comment]
Nou, als ik de wiki pagina met regels bekijk staat daar dit:

**Voorbereiding**
    _Markt is alleen zichtbaar voor marktmeester;_
    Indeling draait niet.

**Activatie**
    Indeling draait niet;
    _Markt nu ook zichtbaar voor ondernemer;_
    Uitslag component: Aangemeld/afgemeld zichtbaar;
    Er zijn mededelingen passend bij deze fase.

**wenperiode**
    Mededelingen passend bij deze fase;
    Indeling draait;
    Uitslag component: Aangemeld/afgemeld zichtbaar;
    E-mail wenperiode wordt verstuurd na indeling.

**Live**
    Indeling draait
    Uitslag component: Uitslag indeling zichtbaar (bijvoorbeeld geen toewijzing of ingedeeld met plaatsnummer(s);
    E-mail toewijzing/afwijzing wordt verstuurd na indeling.
    _Toewijzingen/afwijzingen en opgeslagen voorkeuren zijn zichtbaar voor ondernemer;_

@daan --> dus is ga er van uit dat in de wen periode de markt zichtbaar is voor de ondernemer maar de voorkeuren etc (uit fase Live) nog niet. Maar het is wat onduidelijk in de wiki.
Jij zegt (als ik het goed snap):
Activatie: Markt nu ook zichtbaar voor ondernemer. **Maar niet aanpasbaar dus.**
wenperiode: Markt nu ook zichtbaar voor ondernemer. **Maar niet aanpasbaar dus.**
Live:  Toewijzingen/afwijzingen en opgeslagen voorkeuren zijn zichtbaar voor ondernemer

**Comment by Carlio75** [comment]
opmerking van Eva

**Comment by daan** [comment]
@daan werkt niet aan de pakjekraam.

**Comment by Carlio75** [comment]
Getest, gaat goed!
