### ISSUE TITLE
Tekstwijzing foutmelding bij selecteren te veel markten

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#666]
Wat:
Als een ondernemer meer markten op dezelfde dag selecteerd dan hij en zijn vervangers kunnen bemannen komt er een onduidelijke foutmelding.

Waar:
https://acc.kiesjekraam.amsterdam.nl/aanwezigheid/
testen met 2015022601 en dan 3 markten op 1 dag selecteren

Change: 
Test wijzigen in: U heeft meer dagen geselecteerd dan u (of uw vervanger) aanwezig kunnen zijn. U heeft teveel aanmeldingen voor: ....

<img width="468" alt="Screenshot 2020-05-14 at 13 59 25" src="https://user-images.githubusercontent.com/64955526/81931973-3955d100-95eb-11ea-8f2e-c0dbb57d7d9e.png">

**Comment by tjoekbezoer** [comment]
De gedacht erachter was om de foutmelding zo kort mogelijk te houden, anders wordt hij niet gelezen. De huidige tekst is echter niet duidelijk genoeg, daar ben ik het mee eens.

Aangezien het enkel kan voorkomen als er niet genoeg vervangers geregistreerd zijn misschien dit:

U heeft onvoldoende vervangers voor de volgende dagen: {x}

**Comment by Carlio75** [comment]
Super suggestie! Laten we die doen.
