### ISSUE TITLE
Wijzig tekst flexibel indelen in automatisch indelen

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#668]
### Context
**What** Aanpassen tekst flexibel indelen naar automatisch indelen
**Where** in Plaatsvoorkeuren view van ondernemer
https://acc.kiesjekraam.amsterdam.nl/voorkeuren/16/

### Goal
**Desired behavior or the question to be answered** We tonen nu de tekst "Flexibel indelen" maar die kan wat verwarring oproepen, daarom passen de deze in overleg met het marktbureau aan in "Automatisch indelen".

### Solution space
Zie boven, alleen tekst aanpassen op die plek.

### UX/UI
**Wireframes, UI designs** --> add screenshot voor alle login mogelijkheden
<img width="890" alt="Screenshot 2020-05-25 at 15 11 51" src="https://user-images.githubusercontent.com/64955526/82815865-54053100-9e9a-11ea-9b84-7f116e51b715.png">

### QA 
**AC and scenario**

**Comment by tjoekbezoer** [comment]
Titel aangepast, uitleg verder verduidelijkt.

![image](https://user-images.githubusercontent.com/494128/84756393-08d6cd80-afc3-11ea-8cb5-df8c01c7d515.png)
