### ISSUE TITLE
Melding ondernemer is verplicht deel te nemen aan ingeschreven markten

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#670]
### Context
**What** Als een ondernemer zich aanmeld voor een markt moet hij ook komen die dag.
**Where** op pagina xxx bij ondernemrrs view --> moet nog uitgewerkt worden
**Linked stories** linken aan ticket aanmelden voor meerdere markten 
**How to reproduce**

### Goal
**Desired behavior or the question to be answered**
We willen de ondernemer duidelijk maken dat als hij zicht aanmeld voor een makrt dat hij of een vervanger er dan ook is die dag op die makrt. We willen voorkomen dat ondernemers een soort loterij met plekken gaan spelen. Dit doen we door een tekst te plaatsen

### Solution space - TEKST VOORSTEL
Een aangevinkte dag betekent dat u (of uw vervanger) aanwezig zal zijn. En bent u digitaal ingedeeld op een marktplaats, dan moet u ook komen!  
Bent u er niet terwijl u zich wel digitaal hebt laten indelen? Dan brengen wij het marktgeld bij u in rekening.

(Deze tekst vervangt alle tekst die nu op de https://acc.kiesjekraam.amsterdam.nl/ondernemer/1989030103/aanwezigheid/ staat)

### UX/UI
**Wireframes, UI designs**

### QA 
**AC and scenario**

**Comment by evaleffef** [comment]
Voorbeeld van tekst uit brief:

![image](https://user-images.githubusercontent.com/39556722/84785708-1785aa80-afec-11ea-90a6-ae4322895c79.png)

**Comment by Carlio75** [comment]
Toevoeging nav vragen Jacqueline aan juridische afd Gemeente amsterdam:

-          Tijdelijke en vaste vergunninghouders moeten te alle tijde niet afmelden wanneer ze niet komen, ook wanneer ze in een kwartaal al 10 keer hebben gestaan en besluiten niet te staan op andere vergunde dagen;

-          Enkele opties waarin we deze regel (niet afmelden, wel betalen) wel kunnen opnemen:

o    Een soort disclaimer zetten tijdens het aanmelden bij kies-je-kraam. Dus een soort waarschuwing, in de trant van ‘let op: als je nu aanmeldt voor een plek, en je krijgt deze ook toegewezen en meldt niet af voor 21:00 uur of komt niet opdagen, dan moet je alsnog betalen’.

§  Je kunt de spelregels van digitaal indelen, na het maken van de plaatskeuze, nogmaals attenderen aan de gebruiker (ondernemer), dat hij akkoord gaat met behulp van een ‘vink-balkje’. Net als dat je een ticket online boekt en de algemene voorwaarden (met annuleringsregels) accepteert. Een consent vraag je dan in trant van ‘Weet je het zeker? Zo ja: dan neem je de gevolgen voor lief’.

**Comment by Carlio75** [comment]
Ik wacht nog even op input van jacqueline.

**Comment by Carlio75** [comment]
Voor VPH tonen we deze tekst:
Digitaal ingedeeld? Dan ook komen!
Een aangevinkte dag betekent dat u (of uw vervanger) aanwezig zal zijn.
Wanneer u zich aanmeldt, bent u verplicht om te komen. Bent u er niet? Dan brengen wij het marktgeld de volgende keer dat u op de markt bent in rekening. Indien u niet aan uw betaalverplichting voldoet, zijn wij genoodzaakt uw vergunning in te trekken totdat u heeft betaald. 

Die zal de huidige tekst "Een aangevinkte dag betekent dat u (of uw vervanger) aanwezig zal zijn." vervangen

**Comment by Carlio75** [comment]
Tekstvoorstel voor SOLL volgt

**Comment by Carlio75** [comment]
Geen andere tekst voor soll, die zien hetzelfde als VPH. Dus bij beide rollen deze tekst aanpassen.
<img width="724" alt="Screenshot 2020-08-03 at 11 36 09" src="https://user-images.githubusercontent.com/64955526/89169147-2285a180-d57e-11ea-8c6e-b894ba540054.png">

**Comment by Carlio75** [comment]
@tjoekbezoer kan jij dit ticket oppakken?

**Comment by Carlio75** [comment]
@tjoekbezoer ik zie dit nog niet op acc, klopt dat?

**Comment by Carlio75** [comment]
Getest op acc, is super duidelijk!
