### ISSUE TITLE
Toevoegen branchenummer in vakje met branche kleur

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#689]
Momenteel tonen we een vakje met de kleur van de branche met in dat vakje het kraamnummer.
De martkmeesters willen ook graag het branchenummer zien op de overzichtspagina met de indeling.

Voorstel is om in het vakje met de kleur van de branche ook het branchenummer te zetten en een losser rij ernaast (rechts) te maken met het plaatsnummer.

![Schermafbeelding 2020-07-01 om 14 48 57](https://user-images.githubusercontent.com/64955526/86246655-a4636300-bbab-11ea-820a-a795e59fd005.png)

**Comment by tjoekbezoer** [comment]
Ter referentie: automatisch tekstkleur aanpassen om voldoende contrast met branchekleur te garanderen (http://www.w3.org/TR/AERT#color-contrast)

Nuttige code:

```
function getContrastYIQ(hexcolor){
    hexcolor = hexcolor.replace("#", "");
    var r = parseInt(hexcolor.substr(0,2),16);
    var g = parseInt(hexcolor.substr(2,2),16);
    var b = parseInt(hexcolor.substr(4,2),16);
    var yiq = ((r*299)+(g*587)+(b*114))/1000;
    return (yiq >= 128) ? 'black' : 'white';
}
```

**Comment by Carlio75** [comment]
@tjoekbezoer  wil je dit doorzetten naar productie?
