### ISSUE TITLE
BUG - Kleuren branches printen niet

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#690]
Als je het overzicht van de indeling wil printen komen de kleuren van de branches niet mee.
Zie blijgesloten voorbeeld. Links een screenshot van de website, rechts een screenshot van de "print pdf". Werkt niet in Chrome en in Firefox. Is recent toegevoegd functionaliteit, dus heeft nooit gewerkt.

![Schermafbeelding 2020-07-01 om 15 05 44](https://user-images.githubusercontent.com/64955526/86247374-a7ab1e80-bbac-11ea-9a25-6b597f8ee09d.png)

**Comment by tomootes** [comment]
@Carlio75 

Dit euvel is opgelost door de volgende CSS regel op de table cell toe te passen: -webkit-print-color-adjust:exact. Deze regel werkt voor Chrome. Voor Firefox heb ik de regel color-adjust: exact; toegevoegd. Het zou nu moeten werken in alle niet-stokoude versies van Chrome en Firefox. Moet nog op ACC uitgerold worden!~

**Comment by Carlio75** [comment]
Dit heb ik getest, het werkt nu goed. @tjoekbezoer zou je dit naar productie kunnen pushen?
