### ISSUE TITLE
Tonen van volgende marktdag en kleur wijzigen niet aangemeld

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#704]
Met de verandering van markten op alle dagen naar een enkele dag per markt ziet de opmaak van de Mijn markten (login ondernemer) er onduidelijk uit kwam naar boven bij de laatsate training.

Als je bijv op maandag kijkt naar een zaterdag markt zie je 2x geen makrtdag staan. 
1: is het mogelijk om hier 2x de volgende marktdag te tonen ipv de volgende twee weekdagen?

<img width="911" alt="Screenshot 2020-08-19 at 08 25 45" src="https://user-images.githubusercontent.com/64955526/90599954-0b89b500-e1f6-11ea-9ce2-af77916f4919.png">

2: kunnen we aangemeld groen maken , dan wordt het iets duidelijker of mensen zich wel hebben aangemeld. Met name bij sollicitanten en een groot aantal markten kunnen ze dan in 1 oogopslag zien waar ze zijn aangemeld.

**Comment by tjoekbezoer** [comment]
Staat op ACC.
