### ISSUE TITLE
bug - legenda print niet in kleur

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#713]
Het marktbureau heeft er last van in hun werk. De indeling zelf gaat wel in kleur, alleen de legenda niet.
Ik kan het reproduceren, dus is geen printersetting oid.

**Comment by Carlio75** [comment]
![7d4ed938-1dc3-4b16-a88c-7f6ab657342f](https://user-images.githubusercontent.com/64955526/94567182-773a5580-026b-11eb-8483-afd9e0a9f037.jpg)
![e28ed9f7-b3ed-44e0-ba48-07029fe9d0bc](https://user-images.githubusercontent.com/64955526/94567197-7acddc80-026b-11eb-85b7-599a79299e47.jpg)

**Comment by tjoekbezoer** [comment]
Voor zover ik weet is dit wel een printer instelling. Standaard worden achtergrondkleuren niet geprint, dit moet aangevinkt worden in het print dialoogscherm.

Dit was eerder niet nodig realiseer ik me nu, omdat de CSS code anders gestructureerd was. Ik begreep toen niet waarom, maar dat was natuurlijk om dit issue te omzeilen.

Bovenstaande oplossing zal voor nu echter ook werken.

**Comment by Carlio75** [comment]
Gestest en is idd het geval!
<img width="585" alt="Screenshot 2020-10-06 at 10 06 32" src="https://user-images.githubusercontent.com/64955526/95175568-f542b300-07bb-11eb-9758-1747202f781f.png">

<img width="588" alt="Screenshot 2020-10-06 at 10 06 38" src="https://user-images.githubusercontent.com/64955526/95175597-fecc1b00-07bb-11eb-86cf-cace0d38802e.png">


<img width="706" alt="Screenshot 2020-10-06 at 10 06 44" src="https://user-images.githubusercontent.com/64955526/95175517-e8be5a80-07bb-11eb-83dd-f8bf1f586379.png">

**Comment by Carlio75** [comment]
Ik sluit dit issue, doorgegeven aan de markt welke settings ze moeten aanpassen.
