### ISSUE TITLE
Bug - afmelden ondernemer als Marktmeester is kapot

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#716]
Stappen:
- log in als marktmeester
- ga naar een makrt
- klik op de conceptindeling (stap 1)
- selecteer een ondernemer (stap 2)
- klik op aanwezigheid (stap 3)
- vink een markt uit (stap 4)
- markt is uitgezet, klik op bewaar (stap 5)
- error (stap 6)

Bij deze error (die te zien is op ACC) moet je opnieuw inloggen en is de aanpassing ongedaan gemaakt. Op PROD krijg je een generieke error te zien.

Getest in diverse browsers, in incognito modus, met verschillende accounts (persoonlijke marktmeester account en generieke marktmeester account), iedereen met een marktmeester account krijgt de error. Bij 1 persoon die inlogt als marktmeester gaat dit wel goed, maar als iemand anders inlogt met dezelfde account gaat het daar verkeerd. Dus het lijkt met caching te maken hebben dat het bij die ene persoon wel goed gaat.
Ondernemers kunnen dit wel aanpassen in hun eigen account, dus het lijkt echt alleen een probleem te zijn met marktmeester accounts.

<img width="541" alt="stap 1 conceptindeling" src="https://user-images.githubusercontent.com/64955526/95050877-95310b80-06ec-11eb-849f-ef61008ddd33.png">
<img width="552" alt="stap 2 klik op ondernemer" src="https://user-images.githubusercontent.com/64955526/95050880-96facf00-06ec-11eb-9814-bc900fe413f2.png">
<img width="560" alt="stap 3 aanwezigheid" src="https://user-images.githubusercontent.com/64955526/95050882-995d2900-06ec-11eb-86fd-2cb672008d1e.png">
<img width="569" alt="stap 4 vink markt uit" src="https://user-images.githubusercontent.com/64955526/95050886-99f5bf80-06ec-11eb-8e0b-41e3c9bfeb76.png">
<img width="586" alt="stap 5 uitgevinkt" src="https://user-images.githubusercontent.com/64955526/95050888-9b26ec80-06ec-11eb-959b-015f11f4c961.png">
<img width="1331" alt="stap 6 error" src="https://user-images.githubusercontent.com/64955526/95050889-9bbf8300-06ec-11eb-98a9-21d608be9131.png">

**Comment by tjoekbezoer** [comment]
Het probleem zat niet in de rol van de gebruiker: ook bij marktondernemers trad dit op. Het is mij niet duidelijk hoe dit eerst wel heeft gewerkt, want er zat een fout in de datastructuur waardoor de input data van het formulier niet verwerkt kon worden.

De bugfix staat op acceptatie.
