### ISSUE TITLE
Instellen verplicht per branche (per markt)

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#719]
**Wens:**
Als medewerker van IV wil ik aan kunnen geven of een branche of een bakplek verplicht is omdat ik het marktbureau soms op bepaalde plekken alleen bepaalde branches wil hebben staan.

**Huidige locatie: branches.json**

**Acceptatie criteria:**
Kunnen instellen bij:
- bij een branche
- bij een bak
- op marktniveau
- keuze uit wel of niet
- foutmeldingen bij verkeerd gebruik

**Hoe test je dit?**
A
- kies een branche en zet hem op verplicht
- pak een test sollicitant met een ANDERE branche dan de verplichte branche
- stel de voorkeursplek van die sollicitant in op een verplichte brancheplek
result: ondernemer wordt NIET op die plek gezet

B
- kies een branche en zet hem op verplicht
- pak een test sollicitant met een DEZELFDE branche dan de verplichte branche
- stel de voorkeursplek van die sollicitant in op een verplichte brancheplek
result: ondernemer wordt WEL op die plek gezet

**Comment by milovanderlinden** [comment]
Done. Op een of andere manier kan ik dit issue zelf niet op done zetten, vandaar even als comment.

**Comment by Carlio75** [comment]
Werkt lokaal, next step is overzetten naar de ACC omgeving van Datapunt. Dit proces is in gang gezet.
