### ISSUE TITLE
Aanpassen lijst generic  branches (omschrijving, nummer, afkorting, kleur)

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#733]
**Wens:**
Als medewerker van IV wil ik aan kunnen geven of een welke kleur, id en naam een branche heeft. Zodat ik dit later terug kan laten komen in de indeling en de legenda.

**Huidige locatie: branches.json (niet binnen een marktset)**

**Acceptatie criteria:**
In te stellen per branche:
brancheId	"101-agf"
number	101
description	"AGF"
color	"#73ab4f"

- branches kunnen toevoegen, aanpassen en verwijderen
- van toepassing op alle markten

**Hoe test je dit?**
- pas een kleur aan en kijk of deze meeveranderd

**Comment by Carlio75** [comment]
@milovanderlinden reminder: dus kleurenprikkers bij de generieke lijst. En per markt aanpassen dmv pull down (kleuren etc is niet nodig per markt).

**Comment by milovanderlinden** [comment]
Done. Deze is gereed voor test.

**Comment by Carlio75** [comment]
getest en done
