### ISSUE TITLE
Systeem lijkt maximalisatie te negeren

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#760]
Systeem deelt ondernemer in op plek die gemaximeerd is en waar max is bereikt
"Nu zag ik op de conceptindeling voor de woensdag 11-11-20 dat sollicitant ZZ weer op NIET AGF plaatsen staat ingedeeld terwijl alle AGF plaatsen bezet zijn door vasteplaatshouders. Ik heb bij de vaste AGF ondernemers hun profiel aangepast naar AGF, zodat in mijn theorie sollicitant ZZ op basis van de maximering AGF geen plaats zou krijgen."

**Case**
Maximum van 14 AGF (101) plekken, ingenomen door onderstaande ondernemers die allemaal een vaste plaats hebben
Dappermarkt woensdag - 11-11-2020
omgeving: productie (ivm down zijn van ACC)

**Gegevens gebruikt voor de case**
VPH die AGF zijn:

1. **vpl - sollnr. 297** - plaatsen 30, 32 - settings op AGF - GEEN extra plekken - GEEN plaatsvoorkeuren - NIET automatisch indelen
2. **vpl - sollnr. 49** - plaatsen 65, 67 - settings op AGF - GEEN extra plekken - GEEN plaatsvoorkeuren - NIET automatisch indelen
3. **vpl - sollnr. 174** - plaatsen 105, 107  - settings op AGF - GEEN extra plekken - GEEN plaatsvoorkeuren - NIET automatisch indelen
4. **vpl - sollnr. 2** - plaatsen 147, 149 7  - settings op AGF - GEEN extra plekken - GEEN plaatsvoorkeuren - NIET automatisch indelen 
5. **vpl - sollnr. 14** - plaatsen 159, 161   - settings op AGF - GEEN extra plekken - GEEN plaatsvoorkeuren - NIET automatisch indelen
6. **vpl - sollnr. 1** - plaatsen 183, 185   - settings op AGF - GEEN extra plekken - GEEN plaatsvoorkeuren - NIET automatisch indelen
7. **vpl - sollnr. 349** - plaatsen 228, 230  - settings op AGF - GEEN extra plekken - GEEN plaatsvoorkeuren - NIET automatisch indelen

AGF zit dus aan de MAX van 14 plekken met bovenstaande ondernemers. Maar toch wordt in de voorindeling ondernemer ZZ ingedeeld op plek 20 en 22 die geen AGF plek zijn. Daarmee gaat het systeem voorbij aan de AGF max van 14 plekken.
 
**ondernemer ZZ  SOLL - nr 262**

DATUM - 11-11
MARKT - DAPP-WO
2 plekken nodig - GEEN extra plekken - plaatsvoorkeuren 183 en 147 - WEL automatisch indelen
BRANCHE - AGF -  EVI - UIT - BAK - UIT

![Screenshot 2020-11-10 at 16 10 21](https://user-images.githubusercontent.com/64955526/98695384-dca55a00-2372-11eb-854b-5f8473d43230.png)

**Comment by Carlio75** [comment]
Ik denk dat dit komt door de manier waarop de json is ingevuld. Dat ga ik nu even doorstesten.

**Comment by Carlio75** [comment]
Lijkt niet meer voor te komen, maar we kunnen dat niet met 100% zekerheid zeggen, dus tickets blijft open staan tot we zeker kunnen zeggen dat dit niet meer voorkomt. Maar lijkt met de change in de indelingslogica van eind november verdwenen te zijn.

**Comment by evaleffef** [comment]
Situatie nagebouwd op ACC en komt sinds de laatste wijziging in de berekening niet meer voor.
