### ISSUE TITLE
Toewijzing conservatief indelen niet duidelijk

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#761]
Op dit moment komt het soms voor dat een ondernemer wel/geen meerdere plekken krijgt en kan de marktmeester niet zien of dit met een conservatieve indeling te maken heeft. 

Daarom de wens om de info in de wiki uit te breiden en te tonen welke indeling er is toegepast.

Bij conservatief indelen zijn een aantal dingen niet duidelijk, die we graag willen toevoegen aan de wiki:
- welke plaatsen worden in conservatief indelen meegenomen? Zijn dit alle plekken op de markt, of alleen de niet gebrancheerde plaatsen etc.
- op welk moment in de berekening wordt gekeken naar conservatief indelen en wordt het toegepast
- wat is het omslagpunt bij conservatief indelen, maw wanneer gaat het systeem over op conservatief indelen.

Aanvullende vraag: kunnen we ergens tonen welke indeling is toegepast, zodat de marktmeester kan zien waarom ondernemers wel/geen meerdere plekken hebben gekregen.

**Comment by evaleffef** [comment]
Aanvulling: het gebeurt nu soms dat een AGF-er wordt afgewezen terwijl het maximum aantal AGF plaatsen nog niet bereikt is. Meestal is het dan zo dat een andere AGF-er wel 2 plaatsen heeft gekregen (terwijl ze er beide 1 hadden moeten krijgen volgens de instellingen) Mijn vermoeden is dat in het begin van de berekening bepaald wordt dat er optimistisch wordt ingedeeld, zodat ondernemers direct 2 plaatsen krijgen, wat in combinatie met verplichte branche die gemaximeerd is niet altijd handig uitkomt.
