### ISSUE TITLE
Aanpassen rijen inc kramen  (per markt) (vervolg op #721)

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#769]
**Wens:**
Als medewerker van IV wil ik per pagina instellen welke kramen er te zien zijn en hoe die pagina er uit moet zien omdat ik zelf wil bepalen hoe de marktmeester de indeling ziet.
Als medewerker van IV wil ik kramen in blokken kunnen zetten omdat ik wil dat die kramen aaneengeschakeld (of niet) worden ingedeeld. Een of meerder blokken samen vormen een rij.

Blokken kramen kunnen worden gescheiden door loopjes.

**Huidige locatie blokken: geografie.json**
**Huidige locatie pagina indeling : paginas.json**

**Acceptatie criteria:**
Kunnen instellen bij:
- per markt
- test dat er geen obstakel in een gesloten rij/blok kan staan
- de kraam moet ook voorkomen in de locaties.json en de pagina.json
- foutmeldingen bij verkeerd gebruik
- Markt kan bestaan uit meerdere rijen
- pagina bestaat uit 1 set rijen
- rije kan bestaan uit meerdere blokken
- foutmeldingen bij verkeerd gebruik
in relatie met: https://github.com/Amsterdam/fixxx-pakjekraam/issues/722

**Per pagina**
- pagina title

**Per rij**
- locatie rij op pagina (block-left of block-right)
- rij naam
- Straatnaam begin rij
- Straatnaam begin rij
- kramen in rij (moeten ook bestaan in geografie.json en locaties.json)

**Hoe test je dit?**
- Maak een rij van 4 kramen, 
- test met opeenvolgende nummers
- test met niet opeenvolgende nummers
- test met kramen die niet voorkomen op de markt
- vul de velden in en kijk of ze goed tonen
- maak meerdere blokken per group/pagina aan en kijk of het goed past
- test met kramen die niet op de markt staan en kijk of er een foutmelding komt

**Comment by milovanderlinden** [comment]
Dit is een groot issue met heel veel deeltaken. Kun je hier een checklist van maken?

**Comment by milovanderlinden** [comment]
Als het goed is kan deze nu door gebruikers getest worden want feitelijk is dit geen issue maar een use case / test-scenario.

**Comment by Carlio75** [comment]
getest en done
