### ISSUE TITLE
Branchevrij maken van kraam moet ook een optie zijn

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#791]
Als je eenmaal een branche geselecteerd hebt is het niet mogelijk deze kraam weer branchevrij te maken. Dat moet echter wel kunnen omdat lang niet alle kramen een branche hebben.

<img width="471" alt="Screenshot 2020-12-01 at 12 42 57" src="https://user-images.githubusercontent.com/64955526/100736507-219d3900-33d3-11eb-9001-1773b41f52c9.png">

**Comment by milovanderlinden** [comment]
Done

**Comment by Carlio75** [comment]
getest en werkt
