### ISSUE TITLE
Muteerbaar maken van Rij titel

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#793]
De Rij titel is nu fixed (want die haal je op uit de json), maar moet muteerbaar worden want deze is per markt anders en wordt anders gebruikt per marktmeester.
<img width="918" alt="Screenshot 2020-12-01 at 12 43 15" src="https://user-images.githubusercontent.com/64955526/100737705-cc622700-33d4-11eb-8e46-0d5342b3d607.png">

Los daarvan willen we ook graag de kraamnummers tonen, want nu is het niet makkelijk navigeren naar de juiste kraam. Dat is beschreven in ticket: https://github.com/Amsterdam/fixxx-pakjekraam/issues/792

Hieronder wat verschillende smaken van gebruik van rij titels.
<img width="221" alt="Screenshot 2020-12-01 at 12 50 49" src="https://user-images.githubusercontent.com/64955526/100737608-ad639500-33d4-11eb-8de3-d5570c1e89ad.png">
<img width="423" alt="Screenshot 2020-12-01 at 12 50 36" src="https://user-images.githubusercontent.com/64955526/100737613-afc5ef00-33d4-11eb-9413-9dd136b6a4e0.png">
<img width="759" alt="Screenshot 2020-12-01 at 12 51 22" src="https://user-images.githubusercontent.com/64955526/100737649-b9e7ed80-33d4-11eb-8ab2-edc776961e55.png">
<img width="418" alt="Screenshot 2020-12-01 at 12 51 03" src="https://user-images.githubusercontent.com/64955526/100737663-bc4a4780-33d4-11eb-82e2-db0a08594704.png">

**Comment by milovanderlinden** [comment]
Uitgevoerd als onderdeel van verwijderen/toevoegen pagina(rij) titel.

**Comment by milovanderlinden** [comment]
![afbeelding](https://user-images.githubusercontent.com/106038/102097597-6b9c0b00-3e26-11eb-89fe-7cf51c23bd4b.png)

**Comment by milovanderlinden** [comment]
Done

**Comment by Carlio75** [comment]
getest en done
