### ISSUE TITLE
Toevoegen links/rechts aan marktrij-indeling

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#794]
We willen graag per rij tonen of deze links of rechts in Kies je Kraam getoond wordt.
<img width="1020" alt="Screenshot 2020-12-01 at 13 02 32" src="https://user-images.githubusercontent.com/64955526/100738768-637bae80-33d6-11eb-8091-54c5d5798d85.png">

Dit is met name handig voor markten met een wat complexere indeling. Bijvoorbeeld 1 rij, of kramen die in meerdere korte rijen staan.

Links + rechts
<img width="933" alt="Screenshot 2020-12-01 at 13 08 02" src="https://user-images.githubusercontent.com/64955526/100739133-f3215d00-33d6-11eb-8bde-ca3e7a2f4a39.png">

Links + rechts en alleen links
<img width="931" alt="Screenshot 2020-12-01 at 13 05 56" src="https://user-images.githubusercontent.com/64955526/100739143-f6b4e400-33d6-11eb-91b3-9d00d25a3a33.png">

alleen rechts
<img width="934" alt="Screenshot 2020-12-01 at 13 06 03" src="https://user-images.githubusercontent.com/64955526/100739156-f9afd480-33d6-11eb-8f02-7a97b420b946.png">

alleen links
<img width="930" alt="Screenshot 2020-12-01 at 13 06 18" src="https://user-images.githubusercontent.com/64955526/100739166-fcaac500-33d6-11eb-93d0-55d0ba5fc102.png">

**Comment by milovanderlinden** [comment]
Links rechts is wat nu zorgt voor hoe de rijtjes met de "ruggen tegen elkaar" worden gezet (top-left of top-right). Dit moet door de gebruiker te togglen zijn; links óf rechts. blanco bestaat niet.

**Comment by milovanderlinden** [comment]
Done

**Comment by Carlio75** [comment]
getest en werkt
