### ISSUE TITLE
Markt rijen moeten ook kunnen worden opgedeeld in blokken

### ISSUE THREAD

**Issue by Carlio75** [Amsterdam/fixxx-pakjekraam#798]
Rijen van de markt kunnen worden opgedeeld door obstakels, maar soms is een rij opgedeeld in blokken zonder dat er een obstakel tussen staat.
Bij het indelen van de makrt kan een ondernemer met 2 kramen NOOIT worden ingedeeld op 2 kramen naast elkaar die in verschillende blokken staan.

Bijvoorbeeld:
blok 1: kraam 1, kraam 2, kraam 3, kraam 4
blok 2: kraam 5, kraam 6, kraam 7, kraam 8, kraam 9

Ondernemer A heeft 2 kramen. Ondernemer A zal door het systeem in blok 1 worden geplaatst als daar nog 2 kramen naast elkaar vrij zijn. Of in blok 2 als daar nog 2 kramen naast elkaar vrij zijn.
Als kraam 4 (blok 1) en kraam 5 (blok 2) vrij zijn zal het systeem de ondernemer daar NIET plaatsen omdat deze kramen in 2 verschillende blokken zitten.

Wens: maak het mogelijk om de rijen op te delen in blokken. Bijvoorbeeld door een "onzichtbaar" obstakel tussen de blokken te plaatsen die de rij opsplitst.
In de jsons zijn deze blokken terug te vinden in markt.json

<img width="1137" alt="Screenshot 2020-12-08 at 15 13 17" src="https://user-images.githubusercontent.com/64955526/101494724-fcc33b80-3967-11eb-9991-1a34129d40c1.png">

**Comment by milovanderlinden** [comment]
Bijna klaar. Deze zal ik vanmiddag afronden.

**Comment by Carlio75** [comment]
getest en done
